### ISSUE TITLE
Extra delimiters at the end of the record

### ISSUE THREAD

**Issue by anilvenu** [JoshClose/CsvHelper#1031]
Hi I am using CsvHelper to parse csv files into List<dynamic> and from there into a DataTable. However, when I get extra commas at the end of the file (my clients do send that at times and expects me to handle them) I get this error: CsvHelper.ReaderException: An unexpected error occurred. ---> System.ArgumentException: An element with the same key '' already exists in the ExpandoObject.

Here is a very simple example that breaks the reader:
**name,,
anil,,**

Things work fine if I remove a comma from either header or data or both.

            List<dynamic> result = new List<dynamic>();
            using (StreamReader sr = new StreamReader(sourceDataStream))
            {
                var csv = new CsvReader(sr);
                csv.Configuration.HasHeaderRecord = true;
                csv.Configuration.PrepareHeaderForMatch = header => header.Trim();
                csv.Configuration.Delimiter = ",";
                csv.Configuration.MissingFieldFound = null;
                csv.Configuration.IgnoreBlankLines = true;
                csv.Configuration.TrimOptions = CsvHelper.Configuration.TrimOptions.Trim;

                csv.Read();
                csv.ReadHeader();
                while (csv.Read())
                {
                    var record = csv.GetRecord<dynamic>(); /* Exception happens here */
                    result.Add(record);
                }
            }
            LoadToDataTable(result);
        }

**Comment by JoshClose** [comment]
This is happening because it's trying to set an empty string as the property name more than once. An `ExpandoObject` is essentially a `Dictionary<string, object>`, so if you have multiple keys or properties with the same name, it won't work. It uses the header name as the property name.

**Comment by jasonmueller** [comment]
I am running into the same issue.  I understand it's by design (since you're just reading the rows into properties on the `ExpandoObject`).  

I was able to get the rows to read successfully using `reader.Configuration.PrepareHeaderForMatch = h => string.IsNullOrWhiteSpace(h) ? Guid.NewGuid().ToString("N") : h;` which gives each column with an empty name (for my use case) a unique name.  Unfortunately, I'd like to modify some values and then write the CSV back with the original (empty) column headers.  I wouldn't be modifying the fields with empty column headers, but other fields that have column headers would be modified.

Any ideas?  If this seems like a valid use case and it's not supported, I'd be happy to submit a PR but only if it's aligned with your philosophy.  It looks like it _is_ supported if you are mapping to a known type (via NameIndex on https://joshclose.github.io/CsvHelper/mapping#options).

**Comment by JoshClose** [comment]
That works when you are doing `GetField<T>("name", indexOfName)`. You're not able to have two properties with identical names in C# though, which would be the same with an `ExpandoObject`.

What I could do is just ignore fields where the header is empty. Would that work for you?

**Comment by jasonmueller** [comment]
That seems like reasonable expected behavior.  If I'm reading rows into a `dynamic`, I'd probably expect to refer to the columns by property name / key, so not being able to access fields that are "nameless" isn't surprising.  

I assume that I'd run into a similar problem if I had multiple columns with the same name.  I can't reasonably expect that they should be addressable via properties.  I don't have a need to support the "duplicate names" problem though.

Thank you!

**Comment by devchristianschroeder** [comment]
Hi Josh,

I run into this issue - the header is empty and I have to ignore it. I use Jason's workaround at the moment but it looks not so nice:

![image](https://user-images.githubusercontent.com/25476817/42768717-8bc0f958-8920-11e8-82c6-693ba480990d.png)

Do you have an hint for me?

**Comment by devchristianschroeder** [comment]
csvReader.Configuration.PrepareHeaderForMatch = header =>
                {
                    var newheader = header;
                    int i;
                    if (!int.TryParse(newheader, out i) && !string.IsNullOrEmpty(newheader))
                    {
                        newheader = newheader.Replace(" ", "");
                        newheader = newheader.Trim().ToLower();
                    }
                    else
                    {
                        // Workaround https://github.com/JoshClose/CsvHelper/issues/1031
                        newheader = "delete_" + Guid.NewGuid().ToString();
                    }
                    return newheader;
                };
                
                var records = csvReader.GetRecords<dynamic>();

                foreach (var record in records)
                {
                    // Workaround https://github.com/JoshClose/CsvHelper/issues/1031
                    List<string> keys = new List<string>();
                    IDictionary<string, object> temp = record;
                    foreach (var key in temp.Keys.Where(item => item.Contains("delete_")))
                    {
                        keys.Add(key.ToString());
                    }
                    foreach (string key in keys)
                    {
                        temp.Remove(key);
                    }
       
                   // use temp object
                }

**Comment by JoshClose** [comment]
My suggestion is to not use an `ExpandoObject`.

**Comment by bravehartman** [comment]
I figured out a simpler workaround if all the blank columns are at the end of the row.  You can change the header record before calling ReadHeader.  This allows you to remove the blank columns at the end.  Don't try it with beginning or middle columns because it will throw off the column indexes.

using (var csv = new CsvReader(reader))
                {
                    csv.Read();
                    csv.Context.Record = csv.Context.Record.Reverse().SkipWhile(string.IsNullOrWhiteSpace).Reverse().ToArray();
                    csv.ReadHeader();
 
                    var records = csv.GetRecords<dynamic>().ToList();
}

**Comment by sbandaru08** [comment]
I know you mentioned that the above solution is temporary fix if the empty columns are in end but i have this issue even now where i have empty columns in random places
