### ISSUE TITLE
Breaking change when migrating to CsvHelper 7.1.1

### ISSUE THREAD

**Issue by mabead** [JoshClose/CsvHelper#1081]
I am trying to upgrade from 2.16.3 to 7.1.1. After fixing a few easy compilation problems, I am stuck with the following csv reader configuration properties that do not exist anymore:

- SkipEmptyRecords
- IsHeaderCaseSensitive
- TrimFields
- TrimHeaders
- WillThrowOnMissingField

Can you please provide guidance on how to migrate these configuration to the new version of CsvHelper?

Thanks.

**Comment by JoshClose** [comment]
The configs have changed to more generic callbacks so it's configurable for the user, instead of me writing every feature. All the changes are listed in the change log and the configs are documented, but I'll post them here too.

https://joshclose.github.io/CsvHelper/configuration

`SkipEmptyRecords` -> `ShouldSkipRecord`
```cs
ShouldSkipRecord = record => record.All(string.IsNullOrEmpty);
```

`IsHeaderCaseSensitive` -> `PrepareHeaderForMatch`
```cs
PrepareHeaderForMatch = header => header.ToLower();
```

`TrimFields` -> `TrimOptions`
```cs
TrimOptions = TrimOptions.Trim;
```

`TrimHeaders` -> `PrepareHeaderForMatch` or `TrimOptions`
```cs
PrepareHeaderForMatch = header => header.Trim();
// or
TrimOptions = TrimOptions.Trim;
```

`WillThrowOnMissingField` -> `MissingFieldExcpetion`
The default throws a `MissingFieldException`.
```cs
// turn off
MissingFieldFound = null;
```

**Comment by tynorton** [comment]
> `TrimFields` -> `TrimOptions`
> 
> ```cs
> TrimOptions = TrimOptions.Trim;
> ```

I just wanted to mention that we had to use `TrimOptions = TrimOptions.Trim | TrimOptions.InsideQuotes;` to regain full compatibility with 2.16.3.

**Comment by IoTFier** [comment]
Hi @JoshClose  - 
The link  - [CsvHelper-Configuration](https://joshclose.github.io/CsvHelper/configuration) throws an error - 404 - Oh no's! We couldn't find that page :(

Is it supposed to be https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration/ ?

Thanks
