### ISSUE TITLE
headerNames is null in the MissingFieldFound function

### ISSUE THREAD

**Issue by m-murtaza75** [JoshClose/CsvHelper#1110]
Hi,

I have a missing field in the file and when I test it the program gives null exception instead of logging the headerName. When I debug the program I found headerNames have null value but it is not null for the **HeaderValidated** function. Is there anything I'm doing wrong that causing problem.

Here's my code:
```cs
 public List<T> ReadWithRules(string filePath)
        {
            try
            {
                bool hasValidHeaders = true;

                //Need to figure out a way of injecting these
                using (var reader = new StreamReader(filePath))
                using (var csv = new CsvReader(reader))
                {
                    csv.Configuration.RegisterClassMap<TMap>();
                    csv.Configuration.Delimiter = "|";
                    csv.Configuration.IgnoreBlankLines = true;
                    csv.Configuration.TrimOptions = TrimOptions.Trim;

                    csv.Configuration.ReadingExceptionOccurred = exception =>
                    {
                        //logger.WriteLine( $"Bad data found on row '{context.RawRow}'" );
                        Debug.WriteLine($"Bad data found on row '{exception.Message}'");
                    };

                    csv.Configuration.HeaderValidated = (isValid, headerNames, headerNameIndex, context) =>
                    {
                        if (!isValid)
                        {
                            //   logger.WriteLine($"Header matching ['{string.Join("', '", headerNames)}'] names at index {headerNameIndex} was not found.");
                            Debug.WriteLine($"Header matching ['{string.Join("', '", headerNames)}'] names at index {headerNameIndex} was not found.");
                            hasValidHeaders = false;
                        }
                    };

                    //This falls over if there is data missing... need to investigate
                    csv.Configuration.MissingFieldFound = (headerNames, index, context) =>
                    {
                        //logger.WriteLine($"Field with names ['{string.Join("', '", headerNames)}'] at index '{index}' was not found. ");                                           
                        Debug.WriteLine($"Field with names ['{string.Join("', '", headerNames)}'] at index '{index}' was not found.");
                        
                    };


                    var records = csv.GetRecords<T>().ToList();

                    var recordsList = records;

                    if (!hasValidHeaders)
                    {
                        return null;
                    }

                    foreach (var record in recordsList)
                    {
                        record.IsValid = true;
                        _rulesEngine.ImplementRules(record);
                    }

                    return recordsList;
                }
            }
            catch (System.Exception ex)
            {

                throw ex;
            }

        }
```

**Comment by DavidDeSloovere** [comment]
I think you only get the headernames if the row being parsed in the one that contains the headers. For all other rows CsvHelper doesn't know which field is actually missing. 
@JoshClose can you confirm? I'll be happy to update the docs.


Just some info following here, probably irrelevant but I don't want to throw away some findings after testing:
For me, this is what's happening, with DetectColumnCountChanges true:

- Line 47, field missing > ReadingException (An inconsistent number of columns has been detected.) followed by **MissingFieldFound w/ headernames null**
- Line 48, field missing > NO ReadingException, ONLY MissingFieldFound w/ headernames null
- Line 49, field missing > NO ReadingException, ONLY MissingFieldFound w/ headernames null
- Line 50, VALID LINE > ReadingException (An inconsistent number of columns has been detected.) because all column are back now, and the row is read/parsed correctly (as expected)

Then with DetectColumnCountChanges false:

- Line 47, field missing > **MissingFieldFound w/ headernames null**
- Line 48, field missing > MissingFieldFound w/ headernames null
- Line 49, field missing > MissingFieldFound w/ headernames null

**Comment by m-murtaza75** [comment]
@DavidDeSloovere Yeah I think you are right I tried by removing the header field and it is working for the headers row.

**Comment by Jehoel** [comment]
If you look at the current version of `CsvReader.cs` in the two places it invokes `MissingFieldFound` it supplies `null` to the `headerNames` parameter, so I think this is a bug or incomplete implementation: https://github.com/JoshClose/CsvHelper/blob/d8de6bdc63d607715db520606af0062c40c30152/src/CsvHelper/CsvReader.cs

Both call-sites look like this:

			if( index >= context.Record.Length || index < 0 )
			{
				context.CurrentIndex = index;
				context.ReaderConfiguration.MissingFieldFound?.Invoke( null, index, context );

				return default( T );
			}

Of course, the `headerNames` parameter isn't necessary at all as you can get it from `context`.

**Comment by CrispyDrone** [comment]
I'm having the same issue, the `MissingFieldFound` exception is not being thrown.

Is there a current workaround to be able to detect missing fields? Or is the only option right now to check the column count inside the `ReadingContext` after receiving the `ReadingException (An inconsistent number of columns has been detected.) ` message?

**Comment by JoshClose** [comment]
`headerNames` is the name or list of names used to get the field, supplied by the mapping.
```cs
Map(m => m.Foo).Name("Foo", "Bar");
```
In this case, `headerNames` would be `["Foo", "Bar"]`.

The case where `null` is passed in is because the field is being retrieved by index, not name.

`MissingFieldFound` will get called when the name or index for the field doesn't exist. If your csv has 2 columns and you try and get a field at index 6, you'll get that exception. If you try and get a field with name `"Prop1"` and there is no mapping for it, you'll get that exception.
