### ISSUE TITLE
ShouldSkipRecord bug

### ISSUE THREAD

**Issue by ligu** [JoshClose/CsvHelper#1119]
When defining a custom ShouldSkipRecord function, the check runs for the header row as well.
If the actual header is filtered out, the parsing with CsvReader.GetRecords fails, because the lib is using the first record satisfying the filter condition, as a header row, what will be a data row.

Temporary solution is to modify Your custom ShouldSkipRecord, to not skip the header row, but it's not "nice".

**Comment by JoshClose** [comment]
This is the intended behavior. What is your scenario for skipping rows?

**Comment by alkenes** [comment]
Just wanted to make a note.

`csv.Configuration.ShouldSkipRecord = content =>
				{// Configure the reader to only take records that are in the silver plan
					if (content[PlanLevelIndex] == "Silver")
					{
						return false;
					}

					return true;
				};
				
				var records = csv.GetRecords<Plan>();`

I was using the above code to only get plan types that I wanted to work with, I thought that I would be getting the headers as well. I was getting the following exception:
` CsvHelper.HeaderValidationException: Header with name 'plan_id' was not found.`
Adding a check for the name of the header cell in my if statement made sure the header was included which allowed me to read in the csv. Just wanted to show what I suspect the original reporter was thinking and hopefully provide a search result for others with the same problem.

**Comment by PetteriPertola** [comment]
> This is the intended behavior. What is your scenario for skipping rows?

I think that is very weird and misleading for intended behavior. Since you can use the HasHeaderRecord flag, why would you additionally want to process it in the ShouldSkipRecord filter? I find it completely counterintuitive that I have to write logic in my ShouldSkipRecord filter that takes into account the header row, or alternatively avoid using [Name] attributes for my record class members. Logically, the record should refer to the rows in the dataset, not the column names (the header row). 

Sorry for commenting on an old issue, but I just spent half a day figuring out why it doesn't work and finally realized the header row was being excluded due to my row filter.
