### ISSUE TITLE
What happened to CsvWriter.Configuration.QuoteAllFields?

### ISSUE THREAD

**Issue by johnkwaters** [JoshClose/CsvHelper#1180]
Upgraded to latest version and this broke.

**Comment by JoshClose** [comment]
`ShouldQuote` replaces `QuoteAllFields`, `QuoteNoFields`, `QuoteRequiredChars`, and `BuildREquiredQuoteChars`.

You can do this now.
```cs
csv.Configuration.ShouldQuote = (field, context) => true;
```

This is the default implementation. https://github.com/JoshClose/CsvHelper/blob/7f6896ff4775e5962c3462bf5606104926148a36/src/CsvHelper/Configuration/ConfigurationFunctions.cs#L86

I need to update the change log.

**Comment by johnkwaters** [comment]
Thanks that worked!

**Comment by JoshClose** [comment]
The change log has been updated.

**Comment by shinji144** [comment]
Not sure if you're aware, but the documentation still says to use QuoteAllFields, QuoteNoFields, and IgnoreQuotes

**Comment by niico100** [comment]
This broke my project. Suggestion, keep it in and in the implementation hook up to the code you mention (thus abstracting it away from users who don't need granular control).

The more powerful functionality is nice, but I think it makes it more complex and less intuitive than many users need?! You have the added bonus of not breaking existing code.

**Comment by JoshClose** [comment]
The problem is they conflict with each other. Also, if you set `ShouldQuote`, should it ignore the other settings then? Having both makes things really complicated. It also had some hidden behavior before. If you set `QuoteAllFields = true` it would set `QuoteNoFields = false` without you knowing, since they are in conflict with each other. There was a not in the xml comment, but it's still unexpected behavior.

There was a major version bump, which means breaking code, and I try to document all breaking changes in the change log. If you see that a new version is a major version change, check out the change log before you update and see if it will potentially break your code.

The new documentation will be mostly just lots of full examples on doing things. I think I may push it out sooner than later, and just work on adding more as I go. Basically any time there is a question, if I can't point to an example in the docs, then I'll add something.

**Comment by JoshClose** [comment]
I'll put an example in the docs, but it just changes from an assignment of a boolean to an assignment of a function that returns a boolean.

**Comment by AarifSaiyed** [comment]
What if i only want to quote some fields and leave the others unquoted?

**Comment by JoshClose** [comment]
`Configuration.ShouldQuote`

**Comment by adamsproul** [comment]
@JoshClose  - thanks for your work on this project. We, unfortunately, have to deal with XML in our CSV and using the ShouldQuote really helped out
