### ISSUE TITLE
Issue with reading foreign csv

### ISSUE THREAD

**Issue by sparticus1701** [JoshClose/CsvHelper#1188]
With the following CSV content in a file:
Respondent;Gender;GenderWeight
1;1;0,5
2;1;0,5
3;1;0,5
4;1;0,5
5;1;0,5
6;1;0,5
7;1;0,5
8;1;0,5
9;1;0,5
10;1;0,5

When I run the following code:

using (CsvReader csv = new CsvReader(new StreamReader(tempfile), new Configuration() { CultureInfo = CultureInfo.CreateSpecificCulture("de-DE") }))
{
	csv.Read();
	csv.ReadHeader();
	string[] header = csv.Context.HeaderRecord;
}

In this case, I would expect header to have 3 values, but it has only one.  Is this a bug or am I missing something?

**Comment by JoshClose** [comment]
Set your delimiter to `;`.
```cs
csv.Configuration.Delimiter = ";";
```

**Comment by sparticus1701** [comment]
I'm using that as a kludge, but shouldn't setting the CultureInfo be setting that value?

**Comment by AdamDotNet** [comment]
I work with @sparticus1701 -- just FYI.

@JoshClose -- In any case, would it be reasonable, and hopefully not a terrible breaking change, to add a new constructor to `Configuration`? One that would set the following properties:

1. `Configuration.Delimiter`
2. `Configuration.Quote`
3. `Configuration.CultureInfo`
4. More I'm not thinking of?

Using the `CultureInfo` property setter would not change anything else (as it is today) because it might be confusing to lose your settings based on what order you set them (such as `Delimiter` first, then `CultureInfo`, why did my Delimiter change?). So it seems best to only mutate `Delimiter` etc at construction. The parameterless constructor would pass in `CultureInfo.CurrentCulture` to maintain backwards compatibility.

Proposed API might look something like this:

``` csharp
public Configuration()
    : this(CultureInfo.CurrentCulture)
{
    
}

public Configuration(CultureInfo cultureInfo)
{
    maps = new ClassMapCollection(this);
    CultureInfo = cultureInfo;
    Delimiter = cultureInfo.TextInfo.ListSeparator;
    // etc.
}

// No changes to public properties, such as Delimiter, Quote, etc.
// Tweak the private backing fields to not try to come up with defaults any more.
private string delimiter;
// etc.
```

Is this reasonable? I haven't scanned tons of the code, just the `Configuration` class. I'm also no master of culturally aware code or CSV code. 🙂

**Comment by JoshClose** [comment]
It's using `CultureInfo.CurrentCulture`, so it's not using the `CultureInfo` that you set in configuration. Changing `Configuration.CultureInfo` will not change your delimiter. The delimiter is a string, so once it's set from the culture on a new instance, it won't change. Also, the setter for `Configuration.CultureInfo` doesn't change anything else.

I don't want setting the culture to change the delimiter either. I'd really like the delimiter to default to`,` always, but in other cultures, reading and writing files doesn't work by default since most of the files they expect a `comma` separated file to instead have a `ListSeparator`. 

Does that sound reasonable?

**Comment by AdamDotNet** [comment]
I think we had a slight miscommunication of my suggestion. If the proposed constructor is added, and package consumers continue to use the default constructor, the behavior will be **100% the same as it is today**.

Only when a package consumer passes in a `CultureInfo` instance to the proposed new constructor will the delimiter and any other relevant property change. This supports scenarios where an app can be running as `en-US` but still needs to be able to read CSV files from other cultures that may have different delimiters.

I understand that the setter for `Configuration.CultureInfo` doesn't modify anything other than its backing field. I agree it would need to stay that way.

I'm just trying to ask politely for a change that helps support our scenario, and hopefully enables other package consumers as well. You're the package owner, which means you get to decide if a suggestion gets coded in, and you know your code best. I had no intention of disrespect if any was perceived on your end. It was out of respect that I wanted your opinion on the suggestion. If you decide no to the proposed constructor and slight behavior change, then we know what work-around we'll use.

**Comment by JoshClose** [comment]
Oh, I see. No worries, no disrespect was taken. 

Is your suggestion essentially a shortcut for doing this?
```cs
var config = new Configuration();
config.CultureInfo = new CultureInfo("de-DE");
config.Delimiter = config.CultureInfo.TextInfo.ListSeperator;
```

**Comment by AdamDotNet** [comment]
Yeah, shortcutting setting both `Configuration.CultureInfo` and `Configuration.Delimiter` at the same time through the constructor is exactly right.

Admittedly, it's a small thing; I think we just saw CultureInfo as an available property and initially thought that would help us set the Delimiter automatically. Seeing the docs/code, we now understand the behavior better.

To clarify my previous comment about the `Configuration.CultureInfo` setter, in a long winded way, I was trying to defend NOT changing its behavior, citing how it could end up being confusing if its behavior did change.

**Comment by JoshClose** [comment]
I think it makes sense that if you pass a `CultureInfo` into the constructor, that it would use that to set the `Delimiter` instead of `CultureInfo.CurrentCulture`. 

I see an issue though. If this happens, I would think that users would expect that changing the culture via the property `Configuration.CultureInfo` would also change the `Delimiter`. These configs are two separate things that really have nothing to do with each other. The default was to be nice to other cultures, even though CSV is `comma` separated value.

Thoughts? I'm trying to think of a good way to have both. I like your idea, but also think it could confuse people.

**Comment by JoshClose** [comment]
There are a surprising amount of people that are using tab or some other strange delimiter too. `Delimiter` is actually a `string` now because people are using multiple character delimiters.

**Comment by JoshClose** [comment]
My issue with making it read only is the way I always do things is by accessing the configuration through the reader/writer.
```cs
csv.Configuration.Delimiter = ",";
```
Personally I don't like creating the configuration ahead of time and passing it in. I only do it if it needs to be shared across multiple instances of reader/writer.

**Comment by AdamDotNet** [comment]
Sorry, I meant to suggest that `CultureInfo` be read only. `Delimiter` definitely needs to be mutable.

That way, once the constructor sets `Delimiter` based on what it sees with the given `CultureInfo`, users are still perfectly free to modify `Delimiter` again anyway.

Also, your example makes perfect sense. Even if I set the culture to de-DE, it might still be a tab-separated file. 👍

**Comment by AdamDotNet** [comment]
I just ran a quick test. In short, I think it's OK, both from recompiling, and from just dropping in the new DLL containing the new constructor without recompiling a project that depends on it.

Class Library Project called ClassLibrary1:
``` csharp
namespace ClassLibrary1
{
    public class Class1
    {
        private readonly string _name;

        public Class1()
        {
           _name = "Default inside only constructor";
        }

        public string Name => _name;
    }
}
```

Console App called Inheritance_NewConstructor
``` csharp
using System;
using ClassLibrary1;

namespace Inheritance_NewConstructor
{
    public class Inherited : Class1
    {

    }

    class Program
    {
        static void Main(string[] args)
        {
            Inherited inherited = new Inherited();

            Console.WriteLine(inherited.Name);
        }
    }
}
```

Compile both of those, and run with `dotnet Inheritance_NewConstructor.dll`
Result:
> Default inside only constructor

Now change `Class1`
``` csharp
namespace ClassLibrary1
{
    public class Class1
    {
        private readonly string _name;

        public Class1()
            : this("Default with new constructor added")
        {

        }

        public Class1(string name)
        {
            _name = name;
        }

        public string Name => _name;
    }
}
```
Do NOT recompile Inheritance_NewConstructor, but compile ClassLibrary so the dll has the new constructor. Place the new dll in same directory as ConsoleApp and run with `dotnet Inheritance_NewConstructor.dll`
Result:
> Default with new constructor added

I believe that makes it binary compatible. You can also recompile ConsoleApp just fine if you wanted to, so it's compile time compatible as well.

The constructor appears safe to add.

If you choose to remove the setter from `CultureInfo`, then that's definitely a binary breaking change, and a compile time break if consumers were overriding it, given it's `virtual`.

**Comment by JoshClose** [comment]
I won't remove the setter. I want to make the library flexible. Pretty much everything is not sealed and writable, allowing the user to modify as much as possible... and shoot themselves in the foot too, I guess. The only downside to making the library open is lots of changes are breaking.

**Comment by JoshClose** [comment]
Look good?
```cs
/// <summary>
/// Initializes a new instance of the <see cref="Configuration"/> class.
/// </summary>
public Configuration() : this(CultureInfo.CurrentCulture) { }

/// <summary>
/// Initializes a new instance of the <see cref="Configuration"/> class
/// using the given <see cref="CultureInfo"/>.
/// </summary>
/// <param name="cultureInfo">The culture information.</param>
public Configuration(CultureInfo cultureInfo)
{
	maps = new ClassMapCollection(this);
	this.cultureInfo = cultureInfo;
	delimiter = cultureInfo.TextInfo.ListSeparator;
}
```

**Comment by AdamDotNet** [comment]
Yes, looks good to me!
> If you supply a different CultureInfo on construction, the default Delimiter is still going to pull from the CultureInfo. It's a one time default setting that happens on construction.
I will have to note that in the constructor doc.

Do you want to mention that the `CultureInfo` passed in influences `Delimiter` in the XML comment?

Thank you for providing this library. I'm sure it can be hard to deal with user's requests, and preventing breaking changes.

**Comment by JoshClose** [comment]
This is in version 12.1.0 on nuget.

**Comment by JoshClose** [comment]
Hey guys, can you weigh in on issue #1203? Do you see a reason why the default couldn't be a straight up comma?
