### ISSUE TITLE
ConvertUsing ArgumentException

### ISSUE THREAD

**Issue by LGreenberger** [JoshClose/CsvHelper#1191]
I am getting an exception when writing to a csv file when I add a ``ConvertUsing`` to ``Map(m => m.Link)``. ``NotesAuditable.Link`` is a string type. No exception occurs when ``ConvertUsing`` is removed. Am I not allowed to use it for transposing a string property before writing it out?

```
    public class BugReportMap : ClassMap<BugReport>
    {
        public BugReportMap()
        {
            Map(m => m.BugId);
            Map(m => m.Summary);
            Map(m => m.Severity);
            Map(m => m.ImpactOnBusiness);
            Map(m => m.FilersPriority);
            Map(m => m.CostToBusiness);
            Map(m => m.IsDocumentation);
            Map(m => m.IsHardware);
            Map(m => m.Reproduciblity);
            Map(m => m.DateEntered); // .TypeConverter<NullableConverter>().TypeConverterOption.Format("o");
            Map(m => m.WhoFound);
            Map(m => m.ReportedBy);
            Map(m => m.OriginatorSource);

            References<ProductInfoMap>(m => m.ProductInfo);
            Map(m => m.IsLikelyOnOtherModels);

            Map(m => m.DetailedDescription);
            Map(m => m.StepsToReproduce);
            Map(m => m.RelatedBugs);
            Map(m => m.FileAttachments);
            Map(m => m.InstantReplayScript);

            References<BugManagementMap>(m => m.Management);
            References<NotesAuditableMap>(m => m.Auditable);
        }
    }

    public class NotesAuditableMap : ClassMap<NotesAuditable>
    {
        public NotesAuditableMap()
        {
            Map(m => m.Revised);
            Map(m => m.Modified);
            Map(m => m.Link).ConvertUsing(m => $"=HYPERLINK(\"{m.Link}\")"); // This causes an exception.
        }
    }

ArgumentException: Expression of type 'BugBase.Notes.BugReport' cannot be used for parameter of type 'BugBase.Notes.NotesAuditable'

**Comment by JoshClose** [comment]
This is a bug that I believe is not fixable. Certain things won't work when you use `References` in your map. The expression that is created with `ConvertUsing` is mapped to a property. When you use `References` it's mapped to `NotesAuditable.Link`. When you're writing the object though, it uses `BugReport.NotesAuditable.Link`, but it's writing that one object, and just going down the tree for the properties. I think I'll take a look again if there is a decent way to pass the parent property chain down to create the full chain on a `References` call.

The intended way of mapping navigation properties is to do it all in the single object.

```cs
Map(m => m.Auditable.Link).ConvertUsing(m => $"=HYPERLINK(\"{m.Auditable.Link}\")");
```

**Comment by JoshClose** [comment]
No, I still don't see a way of doing it. The expression comes from the `ConvertUsing` parameter which is tied to a property already. I'd have to build up a new expression tree or something. I'm fine with there being the caveat of `ConvertUsing doesn't work if you use References`, since this isn't the intended way of doing it anyways.

**Comment by JoshClose** [comment]
It's recommended to never use it. Some people really felt they needed it in their crazy one off scenario, so I didn't make it internal.

The recommendation is to do property chaining instead.
```cs
Map(m => m.A.B.C.Property);
```

I think the use might have been when there was a class that was repeated several times. Like user records had several addresses, so instead of repeating them, they could write a single address map and reference it multiple times.

I guess the caveat is already in the xml comment for `References`:
> Meant for internal use only. Maps a member to another class map. When this is used, accessing a property through sub-property mapping later won't work. You can only use one or the other. When using this, ConvertUsing will also not work.

**Comment by LGreenberger** [comment]
Thank you for the explanation.
