### ISSUE TITLE
When making some changes to a csv a string field looses its quotes.

### ISSUE THREAD

**Issue by WhiteKarma** [JoshClose/CsvHelper#1287]
Hello @JoshClose,

I have created a simulation of the issue and a repository for it and i invited you to participate. Due to the data itself i cannot share the repo to the public.

Thanks in advance

**Comment by WhiteKarma** [comment]
Hello, 

So the lines of the input file have line breaks inside the quoted field except one. 
The setting i have in configuration is LineBreakInQuotedFieldIsBadData = false;

The files i am importing sometimes have lines breaks in quoted fields sometimes they do not. When i remove the line breaks inside the quoted field in the input file, after writing the output file, the quoted field without the line breaks gets unquoted. 

Can you help?
Thanks in advance.

**Comment by JoshClose** [comment]
Been real busy. I'll try and look soon.

**Comment by marcrocny** [comment]
@WhiteKarma, do the fields contain any other characters (e.g., delimiters) that would require quotes? 

To confirm: are you using CsvHelper to read the original file into C# objects, then using CsvHelper to write the file as well?

**Comment by WhiteKarma** [comment]
@marcrocny , thank you for your answer. The field in question does not contain delimiters that would require quotes. 
Yes: I am using CsvHelper to read and write the files. You can check for yourself, i've invited you to the repo also. 

Thank you,

**Comment by marcrocny** [comment]
Okay, what you're describing would seem to be expected behavior. When a CSV field does not contain reserved characters (line breaks, delimiters) and there is no reason to quote it, CsvHelper will not generate quotes around the data.

So, if you're reading

```
col1 data,"now here is
a line break in a field",col3
```
into an object, the value of `Col2` won't have quotes because they are not considered *part of* the data; rather, they are markers that the contained characters may contain reserved characters. If you remove the line break and write with CsvHelper, it will not emit the quotes because the field no longer contains reserved characters.

---
I did not use your "repo"--it didn't contain code, just a ZIP file. Nothing personal, I'm not going to download, unZIP and execute something from an unknown source.

**Comment by WhiteKarma** [comment]
OK OK, i am removing the zip and placing the source files there.

**Comment by WhiteKarma** [comment]
OK @marcrocny ,
zip file gone and all the source and the input file are there.

 
Thank you

**Comment by WhiteKarma** [comment]
@marcrocny ,

If the quotes are removed from the field, later i get an exception when trying to GetRecord<T> from the resulting stream i get a CsvHelper.MissingFieldException.

Thank you

**Comment by WhiteKarma** [comment]
Is there a way to force the output of quotes around strings even if there is linefeeds etc to escape within the string fields? 

Thank you

**Comment by WhiteKarma** [comment]
OK, i force the quotes forcing a linefeed: 
´´´
prepareStringField = $"{csvReader.GetField(2)}\n";
´´´
Thanks anyway, i won't bug you more with this.
