### ISSUE TITLE
PrepareHeaderForMatch not being called from GetRecords

### ISSUE THREAD

**Issue by madisonscott** [JoshClose/CsvHelper#1305]
Hi there! I'm trying to use `PrepareHeaderForMatch` to allow for a CSV header like this
```
Charge Code,Charge Amount,Effective Date
```
to be used with a Dto object like this
```
private class AllowableCsvDto
{
    public string ChargeCode { get; set; }
    public string ChargeAmount { get; set; }
    public DateTime EffectiveDate { get; set; }
}
```

Here is my parsing code:
```
using (var reader = new StreamReader(csvStream))
using (var csvReader = new CsvReader(reader))
{
    csvReader.Configuration.PrepareHeaderForMatch = (headerName, headerIndex) =>
    {
        var textCulture = new CultureInfo("en-US", false).TextInfo;
        return textCulture.ToTitleCase(headerName).Replace(" ", string.Empty);
    };
    
    var dtos = csvReader.GetRecords<AllowableCsvDto>();
}
```

I have tried stepping through this and when I step past the line that calls `GetRecords` and try to inspect `dtos`, I see that a `HeaderValidationException` was thrown with the message `Header with name 'ChargeCode' was not found.`

I have:

- set a breakpoint within my `PrepareHeaderForMatch` anonymous function and it is never hit
- confirmed that my anonymous function converts `Charge Code` to `ChargeCode`, when it's pulled out as a separate function and run
- confirmed that my CSV header contains actual spaces and not some other weird whitespace character
- tried explicitly setting the delimiter to a comma, but this did not help

Any suggestions?

**Comment by JoshClose** [comment]
I am seeing some issues that I'll have to look into.

For now you could specify the name in configuration.

Mapping:
```cs
csv.Configuration.RegisterClassMap<AllowableCsvDtoMap>();
```
```cs
private class AllowableCsvDtoMap : ClassMap<AllowableCsvDto>
{
	public AllowableCsvDtoMap()
	{
		Map(m => m.ChargeCode).Name("Charge Code");
		Map(m => m.ChargeAmount).Name("Charge Amount");
		Map(m => m.EffectiveDate).Name("Effective Date");
	}
}
```
Attributes:
```cs
private class AllowableCsvDto
{
	[Name("Charge Code")]
	public string ChargeCode { get; set; }
	[Name("Charge Amount")]
	public string ChargeAmount { get; set; }
	[Name("Effective Date")]
	public DateTime EffectiveDate { get; set; }
}
```

**Comment by madisonscott** [comment]
I found my two issues!

1. I added a `.ToList()` after `.GetRecords()`, because evaluation was being delayed. After doing this, my anonymous function was being called.
2. My anonymous function is called on both the CSV header _and_ the members in the class. I don't like the idea of only transforming if the `headerName` contains whitespace, so I'll try your suggestion!

Thank you SO much for the quick response :)

**Comment by madisonscott** [comment]
Header validation seems to be working after remove my `Prepare` function and only adding the `Name` attributes to my `Dto` class, so I think I'll stick with just that, unless you see a reason to also configure the mapping?

**Comment by jamesbascle** [comment]
You can do something like this as your function:

s=> s.ToLower().Replace(" ", string.Empty)

The function is run over both the header and the property name.  Because the property name has no spaces, your ToTitleCase call is changing the property name to "Chargecode" etc.  You need to write code to make both of them result to the same value for matching.

**Comment by JoshClose** [comment]
One or the other, but not both. Attributes actually create a map on the fly when they're used. Mappings are good when you don't have access to change the source of the file being used. I also just prefer them in general, but don't really have a good reason anymore to do so. ;)

I just realized that the property is `Chargecode` and not `ChargeCode` which is why it wasn't working. It does actually change anything accept the comparison between header and property to see if they match. It's safe to remove spaces and make lower or something, which would work for your case.

As James said! His response popped in as I was typing. :)

**Comment by madisonscott** [comment]
Good point, James! I didn't think of that, but I also just changed one of my dto member names to be different from the user-friendly name in the CSV, so I'll stick with the name attributes. Thanks for the help both of you!
