### ISSUE TITLE
Unhandled exception. CsvHelper.MissingFieldException: Field with name 'id' does not exist.

### ISSUE THREAD

**Issue by Mirandatz** [JoshClose/CsvHelper#1430]
**Describe the bug**
CsvReader is throwing a MissingFieldException, but the field does exist.

**To Reproduce**
To reproduce the bug, download, compile and run the code in this repository
https://github.com/mirandatz/jesting

**Expected behavior**
I expected the CsvReader to actually read the records.

**Comment by JoshClose** [comment]
That link gives me a 404 error.

**Comment by Mirandatz** [comment]
I apologise, the repository was marked was private. Please, when you are able, try again.
Thanks in advance.

**Comment by AltruCoder** [comment]
Looks like it is an issue with not having a parameter-less constructor.  See this issue. https://github.com/JoshClose/CsvHelper/issues/920

**Comment by Mirandatz** [comment]
Added parametersless constructor to person, issue persists.

**Comment by JoshClose** [comment]
Your properties don't have setters, so they're not going to get mapped. CsvHelper will have to use the constructor instead. 

Since you supplied a parameterless constructor, that's being used, and not the one with arguments. If you need to keep the parameterless constructor, use `Configuration.GetConstructor` to get the correct constructor.

Since it's using the constructor, it's mapping the names of the constructor parameters. `id`, `name` You'll need to add a `NameAttribute` also.

```cs
public sealed class Person
{

	[Index(0)]
	[Name("id")]
	public int Id { get; }

	[Index(1)]
	[Name("name")]
	public string Name { get; }

	public Person(int id, string name)
	{
		Id = id;
		Name = name;
	}
}
```

If you want the CSV field headers to be capitalized, then you can change how the headers are mapped to your mapped constructor paramer names.

```cs
csvReader.Configuration.PrepareHeaderForMatch = (header, index) => header?.ToLower();
```

**Comment by Mirandatz** [comment]
Adding the attribute [Name] and removing the parameterless constructor allowed me to use get-only properties.
But here something I don't understand: why does't the CsvReader handles casing by default and the CsvWriter does?

**Comment by Mirandatz** [comment]
Also: why doesn't the CsvWriter handle get-only properties but doesn't handle readonly fields?

**Comment by JoshClose** [comment]
It's not using read only properties. It's using the constructor parameters. Since your constructor has parameters, it uses those names for the mapping, which is why you need to have a lower case `id` and `name` for it to work. You could also change the variable names to match the header of the CSV file which are upper case.

**Comment by Mirandatz** [comment]
Thank you for the assistance. I'm closing tis, since there is no bug, just a user misusing the APIs.
