### ISSUE TITLE
Writing double data to csv results in error

### ISSUE THREAD

**Issue by smallprogram** [JoshClose/CsvHelper#1432]
**Describe the bug**
Write a list with double type combined data to a csv file. The original value will be inconsistent with the data written in csv

**To Reproduce**
1. my code
```c#
    public class test
    {
        public double? a { get; set; }
        public double? b { get; set; }
    }
    test t = new test
    {
        a = 16.3,
        b = 22.5
    };
    List<test> list = new List<test>
    {
        t
    };
    using (var writer = new StreamWriter( @".\test.csv" , false, Encoding.GetEncoding("GB2312")))
    using (var csv = new CsvWriter(writer))
    {
        csv.WriteRecords(list);
    }

```
2. Get the contents of the csv file
![image](https://user-images.githubusercontent.com/6050360/70765478-e35bd380-1d95-11ea-9936-227eb1f7eb2f.png)

**Expected behavior**
The content of the csv file I need to get is consistent with the values in my program

**Screenshots**
![image](https://user-images.githubusercontent.com/6050360/70765478-e35bd380-1d95-11ea-9936-227eb1f7eb2f.png)

![image](https://user-images.githubusercontent.com/6050360/70765734-962c3180-1d96-11ea-895d-19f2be23f4e3.png)

**Additional context**
VisualStudio 2019
.net framewokr 4.7.2
Microsoft.CSharp 4.5.0

**Comment by AltruCoder** [comment]
According to issue https://github.com/JoshClose/CsvHelper/issues/1409, it's using round-trip format. This can be overridden in configuration.
```csharp
csv.Configuration.TypeConverterOptionsCache.AddOptions<double?>(new TypeConverterOptions { Formats = new string[] { "" } });
```

**Comment by smallprogram** [comment]
> According to issue #1409, it's using round-trip format. This can be overridden in configuration.
> 
> ```cs
> csv.Configuration.TypeConverterOptionsCache.AddOptions<double?>(new TypeConverterOptions { Formats = new string[] { "" } });
> ```

I don't think this is a good idea. The problem is that the csvhelper class library does not parse the data normally. Instead of manually correcting this error.
I think it should be fixed by csvhelper.

**Comment by JoshClose** [comment]
The default number that is written needs to be round-trip-able. Microsoft says to use `G17` for `Double` and `G9` for `Single` as the round-trip format `R` doesn't always work.

https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-round-trip-r-format-specifier

Here is a bug and the reason it doesn't work.

https://stackoverflow.com/questions/24299692/why-is-a-round-trip-conversion-via-a-string-not-safe-for-a-double

I see your point though. `16.3` being written as `16.300000000000001` is silly. The `R` format doesn't do that.

I'd like to use the `R` format by default, as that is fixed in current .NET Core implementations. I think there needs to be an easy way for people to configure the `G17` and `G9` formats without really knowing what it is. Maybe something like a configuration `LegacyRoundTripFormat` with a description `Uses G17 for Double and G9 for Single round trip format instead of R. Use this if a round trip fails.` Or maybe the defaults should be set using a pre-processor directive.

**Comment by JoshClose** [comment]
I think I'm going to do a test when creating the converter for a `Single` and `Double` and setting an appropriate default. If the round-trip works with `R` it'll use that. If it fails, it'll use the legacy formats.

**Comment by JoshClose** [comment]
I changed it to use `R` if possible.

```cs
defaultFormat = double.TryParse(double.MaxValue.ToString("R"), out _) ? "R" : "G17";
```

I pushed this to nuget in version 12.2.3.

**Comment by smallprogram** [comment]
Good Job
