### ISSUE TITLE
Read multiple errors in a single row

### ISSUE THREAD

**Issue by GodwinJacobR** [JoshClose/CsvHelper#1457]
I'm reading the csv records one by one and whenever the validation fails, a reading exception is thrown which I catch and then log the row number and also the header name and then continue reading the file.
```
csvReader.Configuration.ReadingExceptionOccurred = (ex) =>
{
	string columnName = ex.ReadingContext.HeaderRecord[ex.ReadingContext.CurrentIndex];
	string errorLine = ex.ReadingContext.Row.ToString();

        string errorMessage = $"Unexpected value for the header {columnName} at the line {errorLine}";
        // log....
	return false;
};
```
But when there are multiple errors in a single row, I can see that the readingexception throws an exception only for the first error in the row and then skips reading the row. This means only the first error in the row is logged and the subsequent errors in the row are neglected.

**Comment by mudnug** [comment]
ReadingExceptionOccurred is thrown if the record could not be read. This is per row, not per column. @JoshClose Should we add any additional documentation (or change the exception name)?

**Comment by GodwinJacobR** [comment]
@mudnug  Is there a way to validate per field in each row, catch the exception and then continue the validation.

**Comment by mudnug** [comment]
ReadingException is produced when there is a file format issue like an inconsistent number of columns, or a cell data type that doesn't match the expected data type.

If you're hitting the ReadingException it may be necessary to read individual fields instead of reading entire records

Replace 
```
 using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
 {
     var records = csv.GetRecords<Foo>();
 }
```

with 
```
    using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
    {
        var records = new List<Foo>();
        csv.Read();
        csv.ReadHeader();
        while (csv.Read())
        {
		int? id = 0;
		try
		{
			id = csv.GetField<int>("Id");
		}
		catch (TypeConverterException)
		{
			id = null; // can't parse the field as int
		}
		var record = new Foo
		{
			id = id,
			Name = csv.GetField("Name")
		};
		records.Add(record);
        }
    }
```

`TypeConverterException: 'The conversion cannot be performed. `will be thrown when the individual field cannot be converted to the requested type. You can try `csv.GetField<string>` at that point, or using a null value as I did in this example.
