### ISSUE TITLE
Mapping with parameterless constructor is not mapping properties not within constructor

### ISSUE THREAD

**Issue by philwindsor** [JoshClose/CsvHelper#1482]
I have created the following basic example to show  the issue i'm having.  As you can see the User class has a constructor that takes 3 arguments (camelCase). When parsing the rows region is never mapped. How do I get region to map, do I need to specify a specific configuration setting? It took me a log time to figure out the header names needed to match the constructor camel casing!

```cs
class Program
    {
        class User
        {
            public User(string firstName, string lastName, string email)
            {
                if (string.IsNullOrWhiteSpace(firstName))
                {
                    throw new ArgumentNullException(nameof(firstName));
                }

                if (string.IsNullOrWhiteSpace(lastName))
                {
                    throw new ArgumentNullException(nameof(lastName));
                }

                if (string.IsNullOrWhiteSpace(email))
                {
                    throw new ArgumentNullException(nameof(email));
                }

                FirstName = firstName;
                LastName = lastName;
                Email = email;
            }

            public string FirstName { get; private set; }

            public string LastName { get; private set; }

            public string Email { get; private set; }

            public string Region { get; set; }
        }

        static void Main(string[] args)
        {
            var s = new StringBuilder();
            s.AppendLine("email,firstName,lastName,Region");
            s.AppendLine("billy@bob.com,me,jerk,UK");
            s.AppendLine("you@u.com,me,fork,USA");

            using var reader = new StringReader(s.ToString());
            using var csv = new CsvReader(reader, CultureInfo.InvariantCulture);

            var records = csv.GetRecords<User>();

            foreach (var user in records)
            {
                Console.WriteLine($"Parsing row: {csv.Context.Row}");
                Console.WriteLine($"Email: {user.Email}");
                Console.WriteLine($"First Name: {user.FirstName}");
                Console.WriteLine($"Last Name: {user.LastName}");
                Console.WriteLine($"Region: {user.Region}");
            }
        }
    }
```

produces the following output

```
Parsing row: 2
Email: billy@bob.com
First Name: me
Last Name: jerk
Region:
Parsing row: 3
Email: you@u.com
First Name: me
Last Name: fork
Region:
```

**Comment by JoshClose** [comment]
If there are not properties to set, like if they all have private setters, it should use the constructor instead, which is why the name needs to be camel case to match the constructor arguments. You can change the header matching strategy like this.

```cs
csv.Configuration.PrepareHeaderForMatch = (field, row) => field.ToLower();
```

Currently, you can only do constructor or member maps, but not both. I'm thinking there shouldn't be an issue with having them both at the same time though. This is something I'll have to look into.

**Comment by philwindsor** [comment]
> If there are not properties to set, like if they all have private setters, it should use the constructor instead, which is why the name needs to be camel case to match the constructor arguments. You can change the header matching strategy like this.

I already have logic in PrepareHeaderForMatch so that isn't an issue now, would of been helpful if it was documented somewhere (constructor name matching).

> Currently, you can only do constructor or member maps, but not both. I'm thinking there shouldn't be an issue with having them both at the same time though. This is something I'll have to look into.

I've gone with the "manual" read option for now. I cloned the (CsvHelper) repo yesterday but haven't had a chance to have a good look around. Which classes handle the mapping, can you point me in the right direction please and i'll have a look myself?

Feel free to close this issue for now, we can track progress with the issue I linked. Should the label be changed to question instead of bug?

**Comment by JoshClose** [comment]
`ClassMap<TClass>` is the class you inherit from for a class map. That inherits from `ClassMap` which has the `AutoMap` functions in it. 

CsvHelper object creation works by taking a mapping configuration and generating an expression tree that gets compiled into a delegate. That delegate is executed on every row. All the code for the expression tree compiling is in the `Expressions` folder. There are different classes that are used depending on the type of object that needs to be created. The most common is `ObjectRecordCreator` because it creates normal custom class objects. In that class in method `CreateCreateRecordDelegate` you can see that it looks if parameter maps exists and uses only that if they do.

> Should the label be changed to question instead of bug?

It's not a bug as it's working as designed. It could probably be changed to a feature though.

**Comment by JoshClose** [comment]
I added a feature request https://github.com/JoshClose/CsvHelper/issues/1484
