### ISSUE TITLE
Faster way to skip rows

### ISSUE THREAD

**Issue by junalmeida** [JoshClose/CsvHelper#1578]
I have a very large file, roughly 800,000 lines, and when I try to simply skip lots of rows, it takes more than minute when I am reaching the end of the file. 

Of course that's all related to network, disk and CPU limitations, however, I read the code of `CsvReader.Read` and `CsvParser.Read` and I am wondering if I could gain some performance improvements if there is a way to simply advance to the next line without making any kind of parsing or reading the whole line, just looking for the next EndOfLine byte. 

Do you think you can implement a method to advance to next record instead of reading and parsing the line?

Thank you for your awesome project.

**Comment by JoshClose** [comment]
You can't just look for a newline because a field may contain one or many of them.

I'm not seeing a good way to quickly skip a row. You can't really remove all the options because that could affect what is considered a field.

If you're reading from a network, that will definitely slow things down. In that case, you can increase the buffer size by a large amount and that will definitely speed things up.

There will be a much faster version of the parser using `Span` and `Memory` coming in the future. It's at least 4x faster iirc.

**Comment by junalmeida** [comment]
@JoshClose You mean because we could have a valid "escaped" new line char in a field, right? Yep I agree we can't.  
Ok, thank you for your fast response. 

Do you have a timeframe on when the next version will be production ready? Thank you.

**Comment by JoshClose** [comment]
6 months ago... Covid-19 and a few other things made it so I don't have much time to work on this. I'm hoping to get back into features here pretty soon though. I'd say a couple months at most.
