### ISSUE TITLE
Call to `ValidateHeader` does not detect missing fields 

### ISSUE THREAD

**Issue by junalmeida** [JoshClose/CsvHelper#1580]
**Describe the bug**
Even if I call `ValidateHeader` before processing the entire file, I keep getting `MissingFieldException` due to a mispelled header title.

**Comment by atkulp** [comment]
Same thing (I think).  My csv is missing a mapped name in the header row, yet the HeaderValidated handler never gets called.  No error until (for me) ReadingExceptionOccurred gets called when reading records.

Sample:
```
csv.Configuration.RegisterClassMap<CodeImportCsv.CsvMap>();
csv.Read();
csv.ReadHeader();
csv.ValidateHeader<CodeImportCsv>();
```
^^^ Expect HeaderValidated handler to be invoked
```
var codes = csv.GetRecords<CodeImportCsv>().ToList();
```
^^^ Actually invokes ReadingExceptionOccurred on the first data row

For now, I'm doing a manual quick check based on column count, but it doesn't seem like I should need to:
```
if( csv.Configuration.Maps[typeof(CodeImportCsv)].MemberMaps.Count != csv.Context.HeaderRecord.Length )
  throw new Exception();
```

**Comment by hackf5** [comment]
Can you post the first few lines of your CSV file and your mapping class?

I can see that there is a difference in behaviour between the index and name maps and missing members, but they seem to work in terms reading data.

**Comment by junalmeida** [comment]
Sorry I can't because this is production data, but I can try to peek the code:
Once to initialise: 
```
                    csv.Configuration.PrepareHeaderForMatch = (header, index) => header.ToLower().Trim();
                    var csvClassMaps = ctx.Resolve<IList<CsvHelper.Configuration.ClassMap>>();
                    foreach (var instance in csvClassMaps)
                    {
                        csv.Configuration.RegisterClassMap(instance);
                    }
                    csv.Read();
                    csv.ReadHeader();
```
Then when reading each file (T is generics)
```
                    csv.ValidateHeader<T>(); // <-- this does not throw anything even if there is a missing header.  I am manually catching `MissingFieldException` during the first record reading to abort the processing. 
```

**Comment by hackf5** [comment]
Sorry, I didn't really explain myself well. Can you post a failing test
case with dummy data?

Like changing the names of the columns to col1, col2, ...

The problem is that it's not clear from your description how to replicate
the error.

**Comment by atkulp** [comment]
I ended up having to come up with a hack to get past this and didn't get back to this issue to reply.  It's pretty simple though.

CSV:
```
A,B,C,Z
1,2,3,4
2,3,4,5
```

Valid CSV in every way.

Mapping class:
```
public class MyCsv {
  public int A {get; set;}
  public int B {get; set;}
  public int C {get; set;}
  public int D {get; set;}
  public int Z {get; set;}
}
```
`ValidateHeader()` should fail.  `MyCsv` class declares a property "D" which is not present in the CSV.  D is set to Required in the mapping, so it fails on `MissingFieldException` when it actually reads the rows, but doesn't care about the fact that it's missing from the header.

If you've fixed this already, you can ignore this.  I've been on other projects in the meantime so I haven't had a chance to retest it.

**Comment by atkulp** [comment]
I was on a different project for a bit and I just had some more time to dig into this.  I found the problem.  If you specify an index for the properties, then ValidateHeader() won't throw.  I can't see how it would make sense for this to be by design, so it must be a bug.  I've written an XUnit test to demonstrate the scenario.  If you simply comment out or remove the Index attributes, the test succeeds (ValidateHeader throws).  I hope this helps!

```
public class CsvHelperTest
{
    [Index(0)]
    public int Id { get; set; }
    [Index(1)]
    public string Name { get; set; }
    [Index(2)]
    public Guid GuidThingy { get; set; }
}

[Fact]
public void FailValidationWithMissingHeader()
{

    var data = new List<string[]>
    {
        new[] { "Id", "Name" },
        new[] { "1", "one", "C38D4077-1CD5-446A-BB22-8BA9FEC6A823" }
    };

    var txt = string.Join('\n', data.Select(e => string.Join(',', e)));
    TextReader reader = new StringReader(txt);

    using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture, false))
    {
        csv.Read();
        csv.ReadHeader();
        Assert.Throws<CsvHelper.HeaderValidationException>(() =>
        {
            csv.ValidateHeader<CsvHelperTest>();
        });
    }
}
```

**Comment by hackf5** [comment]
Yes, that was what I was assuming, which was why I wanted to get your mapping code.

I looked through the code that handles `ValidateHeader` and saw how things were treated differently by name and by index. My assumption was that this is by design, but that the design is bad because it is confusing.

The only way to resolve it would be to introduce a new configuration flag, off by default to preserve the existing behaviour, that actually did validation when using indexes.

(PS you can write your own CSV parser in about 20 lines of code that probably does what you want better and faster than most libraries)

**Comment by junalmeida** [comment]
Yeah, I decided to report because it seems like a bug or bad designed method, since it is called ValidateHeader  I expect the validation that occurred in the first row had occured in the ValidateHeader call.

Delaying that validation to the first row reading is not a big deal for me, so I am ok with any approach decided here

**Comment by atkulp** [comment]
@hackf5 Well.. there are a lot of things I _could_ do from scratch!  I'd rather not worry about the edge cases and take advantage of broader testing.  I agree that in a simple 20-liner, I'd know the error more easily!  I just don't understand the logic surrounding indexed columns not throwing the exception.  Maybe I'm misunderstanding the use though.  I assumed that this required that columns with given headers had to be in a given column position.  Name must be column 1.  Thinking about it more though, I suppose it might mean that this allows you to not use headers since you are simply stating that Name is in column 1... so no header needed.  In my case, I still want the file to have headers, I just want to columns to be in the right order.  The better solution for me is to probably just stop requiring any ordering.  If the header is in column _x_, the parser knows to use column _x_ to read that value.  Another solution might be to throw an exception on ValidateHeader() saying "Warning: Headers are not validated when indexes are specified."  Back to backward compatibility though...  Perhaps the new flag is the way to go: `ValidateHeader(bool noReallyPleaseValidateIt)`

**Comment by junalmeida** [comment]
To add, in my case I use header names, and the header order is not important as long as the header names matches the entity used to validate.

**Comment by JoshClose** [comment]
What would be the point of validating the header when using indexes instead of header names? You're not using the header in this case, so what is there to validate?

**Comment by atkulp** [comment]
@hackf5 Well.. there are a lot of things I _could_ do from scratch!  I'd rather not worry about the edge cases and take advantage of broader testing.  I agree that in a simple 20-liner, I'd know the error more easily!  I just don't understand the logic surrounding indexed columns not throwing the exception.  It looks like I misunderstood the use though.  I assumed that this required that column names were specified in the header for usability, but order was required.  Apparently it's one or the other.  Either you use headers and don't care about order, or you care about order and headers are essentially ignored.  It might have been good to throw an exception on `ValidateHeader()` saying "Warning: Headers are not validated when indexes are specified."  A new parameter/flag could make this conform to what I was expecting: `ValidateHeader(bool noReallyPleaseValidateIt)` 😉

@JoshClose For the sake of the my users, it's much more clear to require headers.  I was also specifying order to maintain forward and backward compatibility with an older system.  I don't see a reason why they need to be mutually exclusive and nothing I was seeing indicated that it was an issue.  Now that I see that it's by design, I will drop backward compatibility and go by name only and require the header row.  That means columns can be in any order which would throw off the old version, but the new version won't have an issue with it.

**Comment by JoshClose** [comment]
CsvHelper reads columns in any order if names are used. When writing you should always have an index specified to ensure a correct order. 

If you have both specified, it will use the name for reading, and write the name in that index position. 

If you only have the index specified, it won't default to the name of the property when reading, it'll use the index. When writing, it will use the property name as a default and the position you specify.

**Comment by atkulp** [comment]
So now I'm a little more confused.  Bear with me.

1. If I call AutoMap with no attributes on the properties, does this mean that it's mapped by name-only?
2. If I call AutoMap with an Index attribute on each property, then is it mapped only by index?
3. Then, if I want by-name for read, and by-index for write, I need to skip attributes and hand map? `Map(m => Id).Name("Id").Index(0)`

I'm just not clear exactly what `AutoMap` sets up.  I assumed it would do a by-name always and then include Index too if present as attributes.  That's what I had: Index attributes on properties, then I'd call `AutoMap()`.  If I want by-name read, by-index write, and `ValidateHeader()` on read then I need to map as in #<wbr>3 above?  Do I need to bother with `AutoMap()` at all then?

Sorry for not getting it.  Thanks for your patience!

**Comment by JoshClose** [comment]
You really shouldn't have to call `AutoMap` explicitly. The only time I can see when you'd want to do that is if you are using `ClassMap` and have a very large number of properties. You could `AutoMap`, then make modifications to the properties you want. You might do something like this.

```cs
// Maps the 100 property class automatically.
AutoMap();
// Change the name of a single property.
Map(m => m.MyProperty).Name("My Property");
```

`AutoMap` is automatically called when you don't specify a map at all. This allows you to quickly get results if the properties and names match. You can literally just do this.

```cs
var records = csv.GetRecords<Foo>();
```

If you need to make a few small changes, then you can add a few attributes to modify the mapping behavior.

I'll try to explain the behavior of indexes and names. It's all based on intent. The behavior is slightly different between reading and writing.

**Writing**
1. The order is always done by index.
1. Indexes are always set. If you don't explicitly set an index (via attribute or mapping), the order of the properties are used, which isn't guaranteed by .NET to be the same order that appears in the source code. This is why you should always explicitly set the index if you care about order. If you're just reading and writing using CsvHelper, then it doesn't really matter because header names are used for reading and the order doesn't matter.
1. The names are only used for writing the header. If you don't specify the name, the property name is used.

**Reading**
- No header
  1. Indexes are used as a general rule.
  1. If the index is set and no name is set, the index is used.
  1. If the name is set and no index is set, you'll get an error.
  1. If both index and name are set, the index is used.
- Has Header
  1. Names are used as a general rule.
  1. If the index is set and no name is set, the index is used.
  1. If the name is set and no index is set, the name is used.
  1. If both index and name are set, the name is used.

**Comment by atkulp** [comment]
Thanks.  That adds a lot of detail.  I think it makes more sense to me now.  I'm using AutoMap on classes that I don't want to add attributes to (EF entities) but want to customize behavior.  If I have a class that I own and want to set a custom validator on a property, it seems I would still use AutoMap to get all the defaults and attributes, then add my own config line to set the validation (or anything like that which isn't handled in the attributes).  To be clear, it seems that the only time the framework will call AutoMap is if you don't do any configuration for a class at all, right?

**Comment by JoshClose** [comment]
If you don't register a class map, AutoMap will be used. AutoMap will use the attributes if you've placed them on members.

**Comment by jzabroski** [comment]
> You really shouldn't have to call `AutoMap` explicitly. The only time I can see when you'd want to do that is if you are using `ClassMap` and have a very large number of properties.

This is an interesting design point.  I always call AutoMap and then spell out all my field mappings out of habit.

I think the ideal behavior would be a Roslyn Code Completion Service that could right-click on the first line of a .csv sample file and say Generate CsvHelper.ClassMap<T> and T.  Even better if it had a Resharper-like wizard to chose basic handling of things like spaces in column names and column names that start with numbers as well as column names that contain invalid characters for C# identifier.

Then I would probably not need AutoMap.  Another possible approach:

```c#
[CsvHelper.GenerateFromSampleFile(Filename = "MyDataRows.csv", UseWidestPossibleDataType = true)]
public partial class MyDataRow
{
}
```

This would rely upon defining a partial class and then using Roslyn Code Generator to generate the actual partial class.

You can imagine a similar solution for ClassMap:

```c#
[CsvHelper.GenerateFromSampleFile(Filename = "MyDataRows.csv")]
public partial class MyDataRowClassMap : ClassMap<MyDataRow>
{
}
```

The neat thing about delegating this to code generators would be that CsvHelper breaking upgrades would be transparently handled by CsvHelper in many cases.  

Additionally, as you now have a Filename for the ClassMap, you can imagine a CsvHelper.TestHelper namespace that auto-generates basic tests of your ClassMap for you.

Just some Labor Day thoughts.
