### ISSUE TITLE
EnumConverter no longer works with Int16 Enum types

### ISSUE THREAD

**Issue by rmurdough** [JoshClose/CsvHelper#1620]
We store all of our Enum types as Int16 rather than Int32. CSVHelper is used heavily in our system for data ingest, converting flat rows into C# objects for further processing. These import files have string values which map to Enum types which we further store in our DB as Int16 values. Since version 16.2 all of our imports fail with the error:

Unable to cast object of type '<enum type redacted>' to type 'System.Int32'

This is because our Enums are Int16 and not Int32

**Comment by Renerick** [comment]
I have similar issue with writing. On my tests any type of enum other then Int32 fails with 
```
System.InvalidCastException: Specified cast is not valid.
```
I assume that this problem was introduced with https://github.com/JoshClose/CsvHelper/commit/74cb8d300a63632e498601c4a76dfb2ee9bf0189#diff-ba0288a272a1f17603773597158dd0d6af3a51133713e2b1cb6252ab761e3ce5R51

**Comment by JoshClose** [comment]
I'll fix this right now.

**Comment by JoshClose** [comment]
Fixed in version 17.0.1 on NuGet.
