### ISSUE TITLE
Cannot use `\t` as delimiter

### ISSUE THREAD

**Issue by Saalin** [JoshClose/CsvHelper#1782]
**Describe the bug**
Since 27.0.0 CsvHelper cannot be used to produce TSV.

**To Reproduce**
`
new CsvWriter(textWriter, new CsvConfiguration(CultureInfo.InvariantCulture) { Delimiter = "\t" )
`
throws an exception with message "\t cannot be a WhiteSpaceChar."

Is there any reason in such behavior?

**Comment by rkm** [comment]
Also running into this issue, and I don't think any of the "breaking changes" in the change log are related.

**Comment by JoshClose** [comment]
I'm going to remove `\t` as a default whitespace character.

**Comment by JoshClose** [comment]
In 27.0.1 on NuGet.

**Comment by 21plc** [comment]
Hi folks! 
 Was this bug resolved ?
I've updated from **v.27.0.2** to the latest **v.27.1.0** and faced the same issue with tab and error message  _"  cannot be a WhiteSpaceChar."_
Is there any workaround for that ?

**Comment by JoshClose** [comment]
@21plc What does your config look like?

**Comment by 21plc** [comment]
@JoshClose  I just put there the _Delimiter = tab_ and that's all:
`using var reader = new StreamReader(file.OpenReadStream());`
`var config = new CsvConfiguration(CultureInfo.InvariantCulture) { Delimiter = "\t" };`
`using var csv = new CsvReader(reader, config);`

  I've checked the source code and there is a check-up for Delimiter - when it's one of whitespace chars then config validation is failed. My that's exactly my case, we have the input files formatted in such way.
  So after the downgrade to v.26.1.0 this still working, but any later version > 27.0.0 (including the latest) throws that validation error.

**Comment by JoshClose** [comment]
You have the delimiter set to `\t` and added a whitespace character of `\t`? Whitespace characters are sued for trimming. If you have `\t` for both a whitespace char and delimiter, and have trimming enabled, you'll get bad results, which is why you can't set both. If you don't have trimming enabled, you don't need to worry about whitespace characters.

**Comment by 21plc** [comment]
@JoshClose thanks for info! I'll check that stuff, probably need to manually disable trimming or modify the default (built-in) collection of whitespace chars. Sorry for late response )

**Comment by i2van** [comment]
@JoshClose [This line](https://github.com/JoshClose/CsvHelper/blob/e3d1962f525d4a5dc97e81feb893e3856b0c9bc2/src/CsvHelper/Configuration/CsvConfiguration.cs#L199) does not allow `\t` usage as a delimiter.

**Comment by JoshClose** [comment]
That will happen only if `\t` is in your list of whitespace characters. By default it shouldn't be in there.

**Comment by i2van** [comment]
Yes, I changed them. Thank you!

BTW, see also [related issue](https://github.com/JoshClose/CsvHelper/issues/1855).

**Comment by i2van** [comment]
Lets say I have the [following file](https://github.com/JoshClose/CsvHelper/files/7585110/tabs.csv) where `c2` column's value is `"\t2\t"`.

I use CSVHelper delimiter auto-detection and would like to trim all whitespaces inside quotes:

```csharp
var csvConfiguration = CsvConfiguration
{
  DetectDelimiter = true,
  WhiteSpaceChars = new [] { ' ', '\t' }, // Note \t, otherwise it won't be trimmed.
  TrimOptions     = TrimOptions.InsideQuotes
}
```

It trims `\t` as expected. However, in this case I can not set delimiter to `\t` cause exception will be thrown due to `\t` in `WhiteSpaceChars`.

**Comment by JoshClose** [comment]
Trimming only inside quotes is doable. This will only work with the delimiter and newline. I added a feature request for this. #1913
