### ISSUE TITLE
Bad data found callback called several times

### ISSUE THREAD

**Issue by pushnitsa** [JoshClose/CsvHelper#1873]
**Describe the bug**
When the row contains unescaped, unclosed quote, CsvReader.ReadAsync() and CsvReader.GetRecord<T>() fires BadDataFound callback each

**To Reproduce**
```C#
        [Fact]
        public async Task TestDoubleBadDataFoundCase()
        {
            var errorCount = 0;
            var csvConfiguration = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                ReadingExceptionOccurred = args => false,
                BadDataFound = args =>
                {
                    ++errorCount;
                },
                Delimiter = ";",
            };
            var csv = "SKU;Min quantity;List price;Sale price\r\nTestSku1;2;10.99;9.99\r\nTestSku2;2;10.99;9\r\nXXX;\"9;10.9;9";
            var stream = new MemoryStream();
            using (var writer = new StreamWriter(stream, leaveOpen: true))
            {
                writer.Write(csv);
                writer.Flush();
                stream.Position = 0;
            }
            var textReader = new StreamReader(stream, leaveOpen: true);

            var csvReader = new CsvReader(textReader, csvConfiguration);

            while (await csvReader.ReadAsync())
            {
                csvReader.GetRecord<CsvPrice>();
            }

            Assert.Equal(1, errorCount);
        }

        public sealed class CsvPrice
        {
            [Name("SKU")]
            public string Sku { get; set; }

            [Name("Min quantity")]
            public int MinQuantity { get; set; }

            [Name("List price")]
            public decimal ListPrice { get; set; }

            [Name("Sale price")]
            public decimal? SalePrice { get; set; }
        }
```

**Expected behavior**
BadDataFound calls just once

**Screenshots**
![image](https://user-images.githubusercontent.com/15198683/136048538-20326b35-9a9f-42b6-9c02-e84fe4973bbf.png)

**Additional context**
We use BadDataFound callback for import error reporting. What are we doing wrong? :)

**Comment by craigc39** [comment]
Can confirm this is an issue for me as well. The CSV I am trying to read has quotes in places it shouldn't and sometimes the CSV will actually think it has a row with less columns. So not only will it call _BadDataFound_ twice, it will also call _MissingFieldFound_ once. If you create a list of bad rows (as per the documentation)- it sometimes will have a row that is duplicated 3 times.

In addition to the above bug, the library will send the bad data into the good data despite the error, causing errors where the good data will be utilized (since I am actually inserting this data into a database).

There is definitely a way around this - but it's incredibly hacky. You would have to use the CSV Helper library twice - once to scan the CSV and record the bad rows - including the exact row number where they happen. That way, when you are generating your bad rows list, you can ensure that there are no duplicates. Second time using the CSV Library to read all the rows - and skip any rows that you recorded in bad rows in the scan. That way, the bad rows don't actually end up going into the good rows. I'm about to test out this solution and hoping it works.

**Comment by nCubed** [comment]
Is this bug on anyone's radar? I too am running into the same issue when an extra quote is included in a field. The net result is all following fields for the row are incorrectly mapped due to the column index now being off by one.

IMO, when bad data is encountered, the callback should at least allow us to skip the current row all together. As currently implemented, there is no way to move on to the next row due to the exceptions that are being thrown, re: Missing Fields, or Invalid Conversion.

**Comment by JoshClose** [comment]
I think the correct solution to this would be not allowing continuation after bad data is found. It's in an unrecoverable state most of the time when this happens. A missing ending quote messes up rows.

The reason the callback happens twice is because every call to get the field will cause the callback. The reader calls `shouldSkipRecord(new ShouldSkipRecordArgs(parser.Record))` which causes it to be called. Since the errors are being skipped it is then called again in `GetRecord`.

I will have to see if there is a way to cache the fields that have already been accessed without it causing extra allocations.

**Comment by JoshClose** [comment]
I found a way to cache the fields that doesn't impact performance.

**Comment by JoshClose** [comment]
Fixed in next version.
