### ISSUE TITLE
Include field name or index in Exception when conversion cannot be performed

### ISSUE THREAD

**Issue by twschiller** [JoshClose/CsvHelper#192]
Please include the field name, index, and/or value in the `CsvTypeConverterException` object thrown by the default converter. Without this information, it's difficult to debug when using the NuGet package.

```
CsvHelper.TypeConversion.CsvTypeConverterException: The conversion cannot be performed.
```

**Comment by sumothecat** [comment]
Hi there. Many thanks for the library. Would you reconsider putting this information in the standard exception message? Reading CSVs from "the wild" is a trial and error affair because they are often riddled with errors, which means that we constantly get conversion errors dealing with new sheets. 

I don't understand the rationale for hiding the essential exception message. I shouldn't have to know to catch a specific exception type - and to deal with a custom property - to get the info that I need.

**Comment by NecroFilja** [comment]
I would add that current fix has exception text as single message.
There is no way to extract field name, field value etc except trying to parse this text.

In case we need to show to user localized message with which field and value are wrong - there is no choise. All information are in private properties: namedIndexes, currentIndex etc. 
**This is ugly**

**Comment by JoshClose** [comment]
@NecroFilja Try the beta. There is a custom `CsvHelperException` that is thrown that should contain all the info you're looking for. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvHelperException.cs

**Comment by seiyata** [comment]
Thank you for this great library.
I still see null in e.Data["CsvHelper"] when this exception happens. Any ways to get column name, row number of cell which has the bad data?

**Comment by JoshClose** [comment]
That doesn't exist anymore. You'll need to look in `CsvHelperException.ReadingContext` or `CsvHelperException.WritingContext`.

**Comment by NecroFilja** [comment]
I updated to 7.1.1 and when trying to read "double?" (standard type converter)
I have still TypeConverterException (no CsvHelperException).  But looks like member info I could now find in exception.MemberMapData

**Comment by JoshClose** [comment]
`TypeConverterException` is a child of `CsvHelperException`. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/TypeConversion/TypeConverterException.cs
