### ISSUE TITLE
CsvHelper causes MSBuild to copy old versions of Microsoft.Bcl.AsyncInterfaces despite newer version being installed

### ISSUE THREAD

**Issue by IIFE** [JoshClose/CsvHelper#2026]
Hi.

I have a project in my solution that uses CsvHelper. I also install the latest version of `Microsoft.Bcl.AsyncInterfaces` within that project. I have another project that also references the latest version of `Microsoft.Bcl.AsyncInterfaces`, but not CsvHelper. The problem I'm finding is due to CsvHelper depending on version 1.0.0.0 of `Microsoft.Bcl.AsyncInterfaces`, MSBuild copies an old version of that DLL, rather than the latest one. The strange thing is that if I remove CsvHelper.dll physical file from my bin folder, I end up with the correct latest version of `Microsoft.Bcl.AsyncInterfaces`. It's only when CsvHelper.dll physical file exists in my bin folder that the issue occurs.

This issue is very similar to [this one](https://docs.microsoft.com/en-us/answers/questions/634312/msbuild-copies-dlls-from-its-currentbin-folder-and.html). I have installed the latest BCL library in my project as suggested, but it doesn't seem to make a difference. For some reason MSBuild always tries to copy an old version of the BCL library when CsvHelper.dll exists in bin folder.

I don't get that issue with other packages that depend on an old version of the BCL library, so I'm wondering if there is an issue in the packages structure of CsvHelper?

Thanks.

**Comment by jzabroski** [comment]
@IIFE  I am pretty sure the issue is you are not familiar with how .NET handles assembly conflicts when a csproj references conflicting dependencies.  The reason removing CsvHelper.dll helps probably has to do with some DI registration steps in your code base, but it is hard to know without example code.

The broader problem is with .NET Standard and how it handles "out-of-box" packages that every other project in the nuget ecosystem has a PackageReference to, such as Microsoft.Bcl.AsyncInterfaces.  The immediate workaround is to handle the assembly load event for this dependency to point to 7.0.0 and regression test that it does not break CsvHelper.  The clean workaround is to not reference CsvHelper from a netstandard2.0 project but a net6.0 project, thus sidestepping the nightmare that is netstandard2.0

**Comment by JoshClose** [comment]
CsvHelper is looking for >= 1.0.0.0, so any newer version should work with it. I'm creating builds for every .NET release you can download now, so the chances of using netstandard today are slim.

```xml
<TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0;net48;net47;net462</TargetFrameworks>
```

If this is still an issue, open back up and provide some code/project that reproduces the issue.
