### ISSUE TITLE
LineSeparator in CsvHelper Does Not Interpret Literal Strings like @"\n" as Newline Characters

### ISSUE THREAD

**Issue by alinf1999** [JoshClose/CsvHelper#2304]
Description:
When specifying the LineSeparator in CsvHelper as the string @"\n" (a literal string containing the two characters \ and n), the library does not implicitly convert it into the actual newline character \n. Instead, it treats it as a literal two-character string, which causes CsvHelper to fail to parse the CSV file correctly.

Expected Behavior:
The library should correctly interpret @"\n" as a single newline character (\n) when used as the LineSeparator.

Actual Behavior:
The @"\n" string is treated as a two-character literal (\ and n) instead of being interpreted as a single newline character. As a result, the library cannot properly parse the CSV file.

Environment:
Library: CsvHelper
Version: 33.0.1
.NET Version: 7
OS: Windows

**Comment by AltruCoder** [comment]
The issue is not CsvHelper.  The issue is when you use `@` in front of the quotes, it turns it into a [verbatim string literal](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#verbatim-string-literals) which no longer recognizes `\n` as the escape sequence for a `newline` and instead sees it as the separate characters of `\` and `n`.  You can either not use the `@` or put an actual line break between the opening and closing `"`.
```csharp
var config = new CsvConfiguration(CultureInfo.InvariantCulture) {
	NewLine = "\n"
};
```

```csharp
var config = new CsvConfiguration(CultureInfo.InvariantCulture) {
	NewLine = @"
"
};
```

**Comment by AltruCoder** [comment]
And rereading your comments you say that
> The library should correctly interpret @"\n" as a single newline character (\n) when used as the LineSeparator.

The problem is there likely have been people who wanted to use the actual literal `@"\n"` characters as their line separator rather than the `\n` `newline` character.

**Comment by alinf1999** [comment]
it's ok
thanks
