### ISSUE TITLE
Substring in Class Map?

### ISSUE THREAD

**Issue by chadbruels** [JoshClose/CsvHelper#297]
I am curious how to write a substring function in a class map. I assume it would be done inside a ConverUsing block. In my class the value of internalCustomer is a substring of the account value in the text file. 

"9999-999999-999-999-002000-2032600"

In the account above the internalCustomer is the last segment of the account: 2032600. Can you help with the syntax of such a substring function?

```
class Contribution
{
    public string Date {get; set; }
    public string fileID { get; set; }
    public string custName { get; set; }
    public string custNumber { get; set; }
    public double contribution { get; set; }
    public string account { get; set; }
    public string internalCustomer { get; set; }
    public string taxID { get; set; }
}

class ContrMap : CsvClassMap<Contribution>
{
    public override void CreateMap()
    {
        Map(m => m.Date).Index(0);
        Map(m => m.fileID).Index(1);
        Map(m => m.custName).Index(2);
        Map(m => m.custNumber).Index(3);
        Map(m => m.contribution).Index(4).TypeConverter<CsvHelper.TypeConversion.DoubleConverter>();
        Map(m => m.account).Index(5);
        Map(m => m.internalCustomer).ConvertUsing(row =>
            {
                // some kind of substring function??
            });
    }
}
```

**Comment by hellboy81** [comment]
Is `ConvertUsing` suitable for writting CSV files?

**Comment by JoshClose** [comment]
Not currently, no. I want to implement that for 3.0 though.

**Comment by jzabroski** [comment]
I think the correct way to do this in today's version of CsvHelper is just create a class that inherits from `DefaultTypeConverter`.  It may also be strictly faster, since CsvHelper can do a topological sort on all mapped properties and scan the file linearly. I don't see how the `ConvertUsing` approach can discover the topological ordering of properties, because the indexing metadata is stored inside delegate code.  (I suppose you could walk the IL code tree to discover it...)

@JoshClose Does CsvHelper do such sorts based on column indexes? If not, I would be happy to do a PR to fix that.

**Comment by JoshClose** [comment]
I'm not exactly sure what you're asking.

**Comment by jzabroski** [comment]
I figured it out - CsvHelper first has a parser that materializes arrays of strings, and the ClassMap indexes into that.  In that way, you don't care how the ClassMap is specified.

I guess in my head I was assuming a tight coupling between parsing and class mapping, which after reading through the code and thinking about it, I don't see why that would ever be the case / right way to do it.

**Comment by jzabroski** [comment]
I guess there could be a micro optimization in saying "I'm splitting this one csv field into these 5 properties, so just read the csv field once and then delegate to these 5 converters".
