### ISSUE TITLE
Mapping a hierarchy

### ISSUE THREAD

**Issue by vivekrathod** [JoshClose/CsvHelper#347]
I've a simple hierarchy like this
```
    public abstract class Parent
    {
        public string Name { get; set; }
    }

    public class Child : Parent
    {
        public string PetName { get; set; }
    }    
```
I've another class PersistToCsv with a property of type Parent
```
    public class PersistToCsv
    {
        public Parent Parent { get; set; }
    }
```
How should I create a class map for PersistToCsv? I've tried

```
    public class PersistToCsvMap : CsvClassMap<PersistToCsv>
    {
        public PersistToCsvMap()
        {
            References<ParentMap>(e => e.Parent);
        }
    }

    public class ParentMap : CsvClassMap<Parent>
    {
        public ParentMap()
        {
            Map(e => e.Name);
        }
    }

    public class ChildMap : CsvClassMap<Child>
    {
        public ChildMap()
        {
            Map(e => e.Name);
            Map(e => e.PetName);
        }
    }
```

and then I register the class map...
```
   CsvConfiguration csvConfiguration = new CsvConfiguration();
   csvConfiguration.RegisterClassMap<PersistToCsvMap>();
   csvConfiguration.RegisterClassMap<ParentMap>();
   csvConfiguration.RegisterClassMap<ChildMap>();

   PersistToCsv persistToCsv = 
          new PersistToCsv { Parent = new Child { Name = "John", PetName = "Papa" }};

   using (FileStream fileStream = File.Open("family.csv", FileMode.OpenOrCreate))
   using (TextWriter textWriter = new StreamWriter(fileStream))
   using (CsvWriter csvWriter = new CsvWriter(textWriter, csvConfiguration))
   {
        csvWriter.WriteRecord(persistToCsv);
   }
```

This simply writes the properties of the `Parent`, but not `Child`. If I change the mapping for `PersistToCsv` to use the `ChildMap` I get an `System.ArgumentException: Property 'System.String PetName' is not defined for type 'CsvMapper.Parent'
s`
```
    public class PersistToCsvMap : CsvClassMap<PersistToCsv>
    {
        public PersistToCsvMap()
        {
            References<ChildMap>(e => e.Parent);
        }
    }
```

**Comment by JoshClose** [comment]
There is no way to do this. How do you access child? `PersistToCsv.Parent.PetName` won't work because `PetName` is not a property of `Parent`. You'd have to cast to `Child` to be able to access it `( (Child)PersistToCsv.Parent ).PetName`. If you do that cast, you know the type is `Child`, so why not make the property on `PersistToCsv` be type `Child`?

I think you should create a `PersistToCsv` class for every implementation of `Parent` and create a `CsvClassMap` for reach and register them.

Doing this works fine:

```c#
public class PersistToCsv
{
    public Child Child { get; set; }
}
```

What is the purpose of the `PersistToCsv` class?

Also, you only need to register the top most mapping in a hierarchy. Doing `References` in a mapping is adding it as part of that mapping. Registering it would allow you to read/write that type directly though, if you needed that.

I'm sure your case is more complicated and this is just test code, but hopefully this helps. Let me know.

**Comment by vivekrathod** [comment]
Thanks for clarifying that there is no need to register the mapping explicitly if I'm already doing the `References` call in the `Parent` mapping. 

I fail to understand though why this is not possible. Is it that my design is incorrect or is it the limitation of CsvHelper. Let me try to explain the situation. You are right that this is just test code that sort of mimics my situation. I've many implementations of `Parent`. The `PersistToCsv` is a business class that needs to hold references to these implementations, hence the use of type `Parent` as a property of `PersistToCsv`.  Its not practical to have multiple `PersistToCsv` classes one for each `Child`.

**Comment by JoshClose** [comment]
It's a limitation of C#/.NET or object oriented inheritance in general. 

Looking at a parent (abstract) `Type` through reflection, there is no way to tell what the `Type` of the child (implementation) is. It could be absolutely anything. The only way it would work is to look at it at run time through reflection, which is extremely slow.

**Comment by sunayv** [comment]
Where are you registering? In configuration file?
