### ISSUE TITLE
No quotes output with CsvSerializer

### ISSUE THREAD

**Issue by wseguin** [JoshClose/CsvHelper#348]
simplified, my code is below. Even though I specified QuoteAllFields=true, the output fields are not quoted. The "bag" variable is a list of string[]... Should work. Any ideas?

```c#
using (var sw =new StreamWriter(outfile))
using (var csvo = new CsvSerializer(sw, new CsvHelper.Configuration.CsvConfiguration() { Delimiter = ",", TrimFields = true, TrimHeaders = true, BufferSize = 8192, QuoteAllFields = true }))
{
    csvo.Write(headers.ToArray());
    foreach (var rec in bag)
    {
        csvo.Write(rec);
    }
}
```

**Comment by JoshClose** [comment]
You're using `CsvSerializer` and the option `QuoteAllFields` is only used in `CsvWriter`. `CsvWriter` takes objects and turns them into a list of strings. `CsvSerializer` will just turn that list of strings into CSV format. I should probably move the quoting and other CSV logic into the serializer, since the serializer should really have the brains. It's equivalent to the `CsvParser`. 

Anyways, to make a long story short, use `CsvWriter`.

**Comment by StefanBertels** [comment]
Same issue: I just debugged why the quoting was missing and the format was wrong (field with delimiter, unquoted). Switched to CsvWriter (WriteField) now and works fine, but this was unexpected.

Parser and Serializer should really match each other. I use direct writing because I want to write out a record in exact input format without defining every column. I store Context.Record (string[]) for this. Quoting might differ, of course.
