### ISSUE TITLE
References<> in CsvClassMap<> outputs default values for properties of Null References

### ISSUE THREAD

**Issue by KevivL** [JoshClose/CsvHelper#372]
sealed class TestObjectMap : CsvClassMap<TestObject>
    {
        public TestObjectMap()
        {
            AutoMap();
        }
    }

And in the other class which has a reference to this:

    References<TestObjectMap>(m => m.TestReference);

If an object has .TestReference == null, the csv writer still prints a default value for the properties in TestObject. Is there a setting i'm missing to correct this? I think the expected behaviour should be blanks? Trying to be concise, i can post a full working sample if that helps clear my point.

**Comment by JoshClose** [comment]
A full example would help.

If you aren't doing any custom mapping, you don't need to specify a class map. It is autmapped by default.

**Comment by KevivL** [comment]
Working Console below. If you look at the output file, the first row prints 0 for DefaultColumn, while the actual object reference was null. I need the custom map as i need to do some column name prefixing along with custom date time formatting for all DateTime datatypes, which i've excluded from this sample. Am i doing something wrong in extending CsvClassMap<>?

    class TestObject { public string ColOne { get; set; } public int DefaultColumn { get; set; } }

    class TestExtract {  public TestObject TestReference { get; set; } public string MainColumn { get; set; }}

    sealed class CustomMap : CsvClassMap<TestObject>
    {
        public CustomMap()
        {
            AutoMap();
        }
    }

    sealed class TestExtractMap : CsvClassMap<TestExtract>
    {
        public TestExtractMap()
        {
            Map(m => m.MainColumn);
            References<CustomMap>(m => m.TestReference);
        }
    }

    class Program
    {
        private static void Main(string[] args)
        {
            var workingSet = new[]
            {
                new TestExtract {MainColumn = "1"},
                new TestExtract {MainColumn = "2", TestReference = new TestObject {DefaultColumn = 101}}
            };

            var config = new CsvConfiguration();

            config.RegisterClassMap<TestExtractMap>();

            var filePath = @"c:\temp\testExtract.csv";

            using (var f = new StreamWriter(File.OpenWrite(filePath)))
            {
                var c = new CsvWriter(f, config);

                c.WriteRecords(workingSet);
            }

            Console.WriteLine("Done");

            Console.ReadKey();
        }
    }

**Comment by KevivL** [comment]
Found the culprit - [CreatePropertyExpression in CsvWriter](https://github.com/JoshClose/CsvHelper/blob/dfe907b84f250114f3e30cdce8b0e1583284c058/src/CsvHelper/CsvWriter.cs#L595-601)
Here you're building the expression If reference == null then use default for value types else use the value.

I think this is incorrect... If i'm mapping in a reference, the fact it's a value field is less relevant than the fact it came through a reference. If a referenced entity is null, no way that a mapped field from there takes on a default.
Plus, for a csv writer, i don't think C# default of a type is relevant?

**Comment by JoshClose** [comment]
What do you expect to happen if a reference object is null? All the fields written to be empty?

So instead of 

```
1,,0
2,,101
```
 you would have

```
1,,
2,,101
```

I'm going to have to think about this one... This would be a breaking change, so I can't just introduce it. I could create a configuration option to turn it on though. 

`UseNewObjectForNullReferenceProperties = true`

I can implement this really quickly here...

**Comment by JoshClose** [comment]
So that's not going to work there. The problem is that when creating the condition expression that checks if it's null, it needs to use 1 of 2 values. These values need to be the same type.

Basically, it's doing this:

```cs
var value = isValueType ? default( int ) : null;
```

I think the only way is going to be using a nullable type.

The expressions basically build a a bunch of statements like this:

```cs
WriteField( record.MainColumn, typeConverter );
WriteField( record.TestReference.ColOne, typeConverter );
WriteField( record.TestReference.DefaultColumn, typeConverter );
```

The null checking makes it look more like this:

```cs
WriteField( record.MainColumn == null ? null : record.MainColumn, typeConverter );
WriteField( record.TestReference.ColOne == null ? null : record.TestReference.ColOne, typeConverter );
WriteField( record.TestReference.DefaultColumn == null ? default( int ), record.TestReference.DefaultColumn, typeConverter );
```

There is actually more going on that makes it even more complicated. This is just showing the specific parts we're talking about.

So with every property, it needs to use the property type as is. If your property isn't nullable, then null cannot be used. The value also gets passed to a type converter, and if it's null being passed to the Int32Converter, then it's not going to work either.

I'm not seeing a way around this.

**Comment by KevivL** [comment]
Ah. Okay, if we take a step back, and think of what is least surprising - the whole referencemap system is simply a flattening operation. 
If an employee has a manager and that manager has an age, the manager reference is nullable and by consequence the flattened manager_age becomes nullable, you wouldn't model age to be nullable in the first place on a manager.
And that's how i think the flattening should be dealt with here, in those few lines of code you're writing an expression that returns the value of the field, and you're picking the field type as the return. But since it's via a reference, a better return type would be Nullable<ValueType> since that is the effective type of the field. Beyond that the code the follows the path of converting nullable fields right?

I've not used or checked the referenced reading operation (i'm guessing the maps are used to build reading expressions as well), so this might be an issue there as well.

As you said, this would be a breaking change and i don't have a clue about how you release them :),  but i think this behavior is more natural and should be the way to go.

**Comment by JoshClose** [comment]
I'll see if it'll work to use a nullable when the type is a value type. I can't use `default( int? )` though for defaults because it'll give me `null` instead of `0`, so I'll have to watch out for that.

I'll see what I can do. I'm on OSX all day, so I won't be able to look at it until about 12 hours from now.

**Comment by JoshClose** [comment]
So, I got this to work.

If the property is a value type, not generic, and the create new flag is off, it'll use `Nullable<int>` instead of `int` when the reference property is null, for all it's properties.

**Comment by JoshClose** [comment]
I think the default should be false in the next release, like you mentioned.

**Comment by JoshClose** [comment]
It's out on NuGet as version 2.13.

**Comment by KevivL** [comment]
Awesome. Thanks for the fix. I set it explicitly to false for now and it works like a charm :+1:
