### ISSUE TITLE
Request: Sepearate NuGet package with only interfaces

### ISSUE THREAD

**Issue by brandondahler** [JoshClose/CsvHelper#374]
I could see benefit in packaging the CsvHelper.ICsv* interfaces and the required configuration classes (or new interface types of those) to reduce the actual reference usage for downstream libraries that use dependency injection to get the actual Csv class instances.

This would require creating a separate project and matching NuGet package, such as CsvHelper.Core, and moving the ICsv* interfaces to it from the main project.  The main CsvHelper package would then need to add a dependency on the new package.

Its possible that I might have time to create a pull request with the required changes, but is this separation something that is acceptable/desired?

**Comment by jamesbascle** [comment]
We currently inject ICsvFactory into the places we need CsvHelper, and we have a Singleton (via IoC container) CSV configuration that we use for internal CSV production/consumption.  I would probably do it in the way you describe if it was provided.

I think one of your issues is going to be a heavy refactor to the configuration stuff to give it interfaces and change all the current consumers of it to take in the Interface.

Another option might be to move the configuration into the Interfaces package as an exception to the interface rule.  But that thing seems to change a good bit, so would cause then interfaces package to need to change a lot, which is the exact opposite of what should be happening.

**Comment by JoshClose** [comment]
What do you mean by

> reduce the actual reference usage

I guess I don't understand the issue. Is the download of the full assembly too large?

**Comment by brandondahler** [comment]
@JoshClose it is not that the assembly is too large or anything, but having the interfaces and the implementation in the same assembly strongly couples dependencies to the implementation version instead of the interface version.  I'll provide a basic example where having separate assemblies would simplify an end-users workflow.

There exists CsvHelper Library, Library B, and Project C.

CsvHelper's latest stable version is 2.13.0.
Library B is dependent on CsvHelper version >= 2.8.0
Project C is dependent on CsvHelper version 2.1.0

When it is decided that Project C needs to use Library B, they realize that they'd need to upgrade their version from 2.1.0 to 2.8.0, which is a pain in the ass because Project C is owned by a large enterprise that requires complete regression testing when upgrading libraries.

On the other hand, theoretically, the interfaces haven't changed since 2.0.0, so CsvHelper's versions are linked against the interface package v2.0.0.  Since the latest version for the interface package is v2.0.0, Library B could just depend on the interfaces package at v2.0.0 (because the library doesn't actually care about the implementation, just that it can use it), and then finally it doesn't matter what implementation version Project C is on.

**Comment by JoshClose** [comment]
Do many other libraries do this? I guess I haven't noticed.

Have you tried this this scenario with CsvHelper? Every released `AssemblyVersion` is `2.0.0.0` and only the `AssemblyFileVersion` changes. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Properties/AssemblyInfo.cs#L42 This should mean that you can use different versions together. http://stackoverflow.com/a/65062/68499

I haven't done a bunch of testing with scenarios, so let me know if I'm mistaken here.

**Comment by brandondahler** [comment]
[Common.Logging](https://github.com/net-commons/common-logging) does this with their [packages](https://www.nuget.org/packages/Common.Logging/) (Common.Logging.Core is their interfaces, Common.Logging is their base implementation, Common.Logging.* is their plugin providers).

Based on my understanding:

*  AssemblyVersion staying the same prevents issues with run-time binding and is used to generate the fully qualified assembly name.
    * When assemblies reference the library, they store the same version despite potentially building against different versions.
    * The reason why BindingRedirects exist is to solve conflicts between assemblies referencing different versions.
    * The negative is that if an assembly is linked against and uses a public method that exists in a newer version, but it is bound at run-time to a version that doesn't have that public method, you'll get a run-time error when it tries to call the method.

* AssemblyFileVersion is a way to mark that the file is not the same exact file for another one.
    * Used to check equality between builds without checking the bytes.
    * For example, it could be used to identify that while one assembly is x86 and the other is x64, they where built from the same source and at the same time and are therefore equivalent.

* AssemblyInformationalVersion is a way to give a friendly name to an otherwise unfriendly numbers-only version.


The issue that I'm suggesting to solve is a layer above -- NuGet package manager's dependency resolution.  You'll be able to decouple the versioning between CsvHelper's internal implementation from the public-facing interfaces.  Since they are decoupled, you could have versioning to the effect of:

CsvHelper 2.0.0 => CsvHelper.Core 2.0.0
CsvHelper 2.1.0 => CsvHelper.Core 2.0.0
CsvHelper 2.2.0 => CsvHelper.Core 2.0.0
CsvHelper 2.3.0 => CsvHelper.Core 2.0.0
CsvHelper 2.4.0 => CsvHelper.Core 2.0.0
Minor interface modification, CsvHelper.Core 2.5.0 created
CsvHelper 2.5.0 => CsvHelper.Core 2.5.0
CsvHelper 2.6.0 => CsvHelper.Core 2.5.0
CsvHelper 2.7.0 => CsvHelper.Core 2.5.0
CsvHelper 2.7.2 => CsvHelper.Core 2.5.0

**Comment by JoshClose** [comment]
What is a potential issue of the way it's currently being done? I'm not understanding why the current way is bad.

I can create multiple libraries that all reference different versions (same AssemblyVersion) and use the interfaces from each, and the project that is running the instance is a different version too. Everything seem to run fine.

When project C uses library B, they shouldn't have to upgrade. They will be passing an instance into a method that meets the interface requirements. They would only have to upgrade if the interface has changed (I think), but they would have to do that if they were separated into different assemblies too.

**Comment by jamesbascle** [comment]
I guess it depends on what you mean by issue.  In the .NET world, the
"recommended" or "accepted" best practice to "code to the interface, not
the implementation" is to have an assembly that contains all your
Interfaces and the POCOs/DTOs and enums that move those interfaces take in
as parameters, or return as results.  Anything more complex than a DTO/POCO
should also be represented by an interface.

Thus, any assembly that desires to use a package, will take a dependency on
the interface package.  The implementation package will also take that
dependency.  Then the actual applications, which use both packages, will
resolve at either runtime or compile time which implementations of your
interfaces to use.

In this way, we get quite loose coupling - the component assemblies are
forced to code to the interfaces, the applications can use both of them
without fear of toe stepping, and everything can be done "the right way".

**Comment by jamesbascle** [comment]
I should add, that this would help greatly, anyone who wanted to swap out
CSVHelper with another CSV Parsing library (not sure why, but for the sake
of argument...) all they have to do is implement the Interfaces provided,
most likely via an adapter class from their newly chosen library to the
interfaces in CsvHelper's interface assembly.

**Comment by JoshClose** [comment]
I guess I don't see why you can't do that when the interfaces are included in the same assembly.

**Comment by JoshClose** [comment]
The reason I'm hesitant is because of complexity; mostly on my end. 

1. It's nice to have a single assembly to deploy. 
2. I have 8 projects to maintain already. 4 implementations for different .NET version, then 4 test projects for them. This would add another 4 assemblies to maintain.

**Comment by jamesbascle** [comment]
I would think you should only have to have the interfaces in one project,
maybe a PCL, I would think, which all the other projects use and implement,
causing a reduction in actual code to maintain, instead of duplicating the
interfaces across all 4 projects.

In the following, => represents "is used by", and a letter represents an
Assembly.  Assume all of these are using version 2.* of CSVHelper.

A => B => C => D => E => F => G

Currently, if you release a bug fix, users of CsvHelper who maintain
project G, must update, in sequence A, B, C, D, E, F, G's version of
CSVHelper to have all the code using the same version of CsvHelper 2.

After all, there's no telling whether or not project C is working around a
bug in CsvHelper's implementation that causes it's unit tests to pass when
using the old version, and fail when using the new.

**Comment by jamesbascle** [comment]
Ahh I see, yeah the 4 projects are for the different .NET versions.  I'm
not entirely sure how it would look if you did what we're talking
about...my gut tells me it shouldn't require more than one more project,
but I may very well be wrong.  I could give it a deeper look if you like to
see if it all works out.

Anyway, I'm signing off.  It's not my project to maintain.  These are the
arguments I would make to anyone about why they should separate interfaces
from implementations in this manner.

**Comment by JoshClose** [comment]
I don't think it should matter on any of the ones that are just using the interfaces. The only one that would have to be updated is the one that is creating the instance that implements the interface; which I think would be G in your example. A through F could use any version, because it's just using the interface portion. The only time you'd have to update them all is if the interface changes; but in that case you'd have to update the interface assembly too if they were separated. 

Currently I'm not seeing a compelling reason to split them out, and will probably stick with leaving them together. To me it seems that the behavior can be the same when together. Separating them will allow for a user to just build upon an interface assembly, but they could do the same thing if the implementation was included; they just ignore it.

I have to get up in 5 hours for work, so I should sign off also. :)

Thanks for the discussion. If you have any more points, I'd like to hear them. If there is an article out there that talks in depth about this that might help me understand better, feel free to link it and I'll take a look.

**Comment by jamesbascle** [comment]
So, after looking into the solution a bit, one of the tough things about doing this with CSVHelper is then CSVConfiguration and CsvClassMap classes.  Since so much logic is wrapped up in them, there would have to be either some gimped, standalone proxy DTOs, or a Factory/Factory method for each on ICsvFactory or maybe an ICsvConfigFactory.

I can recommend you a couple of articles, but as you've stated, it would be a non-trivial undertaking.  I've found this book to be quite good: http://www.amazon.com/Adaptive-Code-via-principles-Developer-ebook/dp/B00OCLLYTY  You can also find some decent answers on the matter on StackOverflow and the web by searching "C# interfaces separate assembly" with some lively debate.

**Comment by jamesbascle** [comment]
Another option for the Config stuff would be some fluent configuration interfaces, which seem to be in vogue, and could provide a nice way to consume CsvHelper, besides enabling this kind of interface segregation.

**Comment by jamesbascle** [comment]
After digging some more, while I still think it a good and worthwhile goal, I have to agree with you, @JoshClose, that it is not practical as a "hey lets do this!" kind of initiative on the project with the current architecture.  As I mentioned before, there would be a LOT of work around the config/map stuff to nail down a good metaphor/paradigm without having to suck in any functionality to the interfaces package.

**Comment by JoshClose** [comment]
I think separating things is great when you're building an application, especially a large one, and I often do it myself. I just don't see a compelling reason to go through the pain in this project in particular.

**Comment by JoshClose** [comment]
What are you looking for as far as a fluent interface? It currently has fluent mapping, but only to a certain point.

```cs
void Main()
{
	var map = new DefaultCsvClassMap<Test>();
	map.Map( m => m.Id ).Name( "The Id" ).Default( 0 ).TypeConverterOption( NumberStyles.Any );
	map.Map( m => m.Name ).Name( "The Name" ).Default( "_" );
}

public class Test
{
	public int Id { get; set; }
	
	public string Name { get; set; }
}
```

You currently can't get back to map. That would require specifying all the details inside map, I think.

How would you like to use it differently than the above example?

**Comment by jamesbascle** [comment]
I actually think map is alright except for the fact that you can't get back to it from the end of one statement in the pipeline.  The friction I see comes from the forced separation of the CsvConfiguration from the ClassMap stuff and the ICsvFactory stuff.

What if you had:
```c#
public class FakeJob : Job
{
    private ICsvFactory _csvFactory;
    public FakeJob(ICsvFactory csvFactory)
    {
        _csvFactory = csvFactory;
    }

    public override RunJob(FakeJobParams params)
    {
    var config =  _csvFactory
    .CreateConfig().Delimiter("\t").HasHeaders().ThrowOnMissingField()
        .AddClassMap<Test>()
            .Map(t=>t.Id).Name("The Id").Index(0).Default(0)
            .Map(t=>t.Name).Name("The Name").Default("_")
        .AddClassMap<Test2>
            .Map(t=>t.Id2).Name("The 2nd Id").Index(0).Default(0);
    //do stuff
    }
}
```
Not actually saying "this is how I want it to look", just throwing it out there as an idea, that could also potentially enable the issue at hand.

**Comment by JoshClose** [comment]
You really can't do

```cs
.Map( m => m.Id ).Name( "The Id" )
.Map( ... )...
```

It would probably be more like

```cs
.Map( m => m.Id, cfg => cfg.Name( "The Id" ).Default( 0 ) )
.Map( m= > m.Name, cfg => cfg.Name( "The Name" ) )
```

The reason is that `Map` needs to return a type that contains the methods for configuration the current map. If it was on a more global level like in your example, doing `.Name( ... )` wouldn't know which map to apply it to.

I'll have to think about adding something like that to the factory. I honestly forgot the factory even existed, lol.

Maybe at the end you could call `.CreateReader( textReader )` and it would return a configured `ICsvReader`.

**Comment by jamesbascle** [comment]
>The reason is that Map needs to return a type that contains the methods for configuration the current map. If it was on a more global level like in your example, doing .Name( ... ) wouldn't know which map to apply it to.

I think it actually could.  The factory being returned from each method call would just need to keep a Stack of CsvClassMap, each of which would keep a stack of CsvPropertyMap, and the call could easily be directed to top of the stack.   You could also just keep a single private field called "CurrentClassMap" or "CurrentPropertyMap" Each time a "pushing action"(.AddClassMap(); .Map()) happens, you just push it on the stack.  You can also use different interfaces, all of which are implemented by your factory, for each separate stage of the configuration pipeline to somewhat restrict what calls are available if need be.

I think a pretty good example of this is the Serilog LoggerConfiguration class.  He stopped short of actually having an *interface* for each thing, and instead implemented them as separate classes.  These are not incompatible strategies by the way, but doing it that way means the classes helping the factory would need references to the thing it helps passed in so that it can return it from its fluent methods.

You've now piqued my curiosity and I may try my hand at this in the coming weeks!

**Comment by JoshClose** [comment]
Lol, ok, cool. I will have to think about it. People have been asking for a way to dynamically create mappings. You currently can, but you modify a map dynamically, and use `DefaultCsvClassMap<T>`. I'm guessing this way would probably please people.

**Comment by JoshClose** [comment]
I don't want to give the user the possibility of getting into a bad state though. Like if they did `Factory.Configure().Name()`. There is no property map set in that case.

I'll see if I can come up with a set of interfaces for an API.

**Comment by JoshClose** [comment]
I'm closing this since the original request isn't going to happen. @jamesbascle is working on implementing the factory stuff he talked about.
