### ISSUE TITLE
Define Headers and Map

### ISSUE THREAD

**Issue by mtherien** [JoshClose/CsvHelper#392]
I like what  you have so far, but unfortunately I don't think I could use it.

It appears that you are defining the column headings by reading the property names in the object.  The problem with this is I need to specify the column names in the file and map fields from the object to that column.

Many times I have a C# object that I need to export to different CSV formats defined by 3rd party vendors. 

Is this feature available and I am not seeing it?

**Comment by jamesbascle** [comment]
The class map objects can define column name using the
Map(x=>x.y).Name("WooImYsName") syntax/methods.  Is this what you're
talking about?

**Comment by mtherien** [comment]
I did find that and did some testing and it did seem to work.  I also found the Index method on the map, so you can control the order.

I still have two problems:
1. Map a property to multiple columns in the CSV file (strange, I know)
2. A a column that doesn't map to anything but a default value.  (this is already logged).

**Comment by jamesbascle** [comment]
For default, you could just make a get only property on your row model
object.

For the map to two columns, you could do the same thing where your second
is a get only property that just returns the value of the first.

You would need a separate read and write class map for this I think though.

**Comment by JoshClose** [comment]
In your scenarios, are you reading or writing?

**Comment by mtherien** [comment]
I am writing a csv.

I could add properties as jamesbascle suggests, but I believe that defeats the purpose.  I don't want to change my object in order to write a CSV export.

**Comment by jamesbascle** [comment]
@mtherien 

Now we really get into differences of opinion possibly.  Because the object you already have is seemingly different in structure from the rows that actually need to be produced, I see the rows that need to be generated for the CSV to be an entirely separate entity from that domain object you're dealing with.  Perhaps, you really do have a separate object/entity here.

You do have some options as it stands though I think, without having to make a new class, or even have a pre-defined class map at all really.  One, is to use an object similar to this (the semantics are unimportant ultimately):

````C#
    public class GenericCsvMapper<T> : CsvClassMap<T>
    {
        public GenericCsvMapper(Dictionary<string, Expression<Func<T, object>>> dict)
        {
            foreach (var expression in dict)
            {
                Map(expression.Value).Name(expression.Key);
            }
        }

        public static GenericCsvMapper<T> CreateFromMappingDefinition(Dictionary<string, Expression<Func<T, object>>> dict)
        {
            return new GenericCsvMapper<T>(dict);
        }

        public static GenericCsvMapper<T> CreateFromMappingDefinition(Dictionary<string, PropertyInfo> dict)
        {
            return new GenericCsvMapper<T>(dict);
        }
        
        public GenericCsvMapper(Dictionary<string, PropertyInfo> dict)
        {
            foreach (var expression in dict)
            {
                PropertyMaps.Add(new CsvPropertyMap(expression.Value).Name(expression.Key));
            }
        }
    }
````

And simply make an anonymous object with the fields you need from the object you have, and generate your mapping at run time using the static factory methods I've shown above.

**Comment by jamesbascle** [comment]
Looks like pushing 1 property to 2 columns is *not* possible right now.  It seems that "last one in wins".

**Comment by JoshClose** [comment]
I added this as a feature request.
