### ISSUE TITLE
DataTable support

### ISSUE THREAD

**Issue by Arithmomaniac** [JoshClose/CsvHelper#400]
An `ICsvReaderRow` is essentially an array of strings, just like an `IDataRecord`. Similarly, an `ICsvReader` is analogous to an `IDataReader`.

It may be more trouble than it's worth to implement these interfaces, but it would be nice if, at a minimum, there was a utility method to add each row of the CSV file as a `DataRow` to a new `DataTable`.

(I'd do a PR, but I'm not sure I have the time)

**Comment by JoshClose** [comment]
Like `ToDataRow()` and `ToDataTable()` methods? My only concern with that is managing the column names. I don't want to put any sort of configuration in place to handle that. The code to do it by hand is pretty small, and you could easily create an extension method to do it. I have example code here. http://joshclose.github.io/CsvHelper/#how-can-i-use-a-datareader-or-datatable-with-csvhelper-

The reason `IDataRecord` and `IDataReader` aren't implemented is because it's several methods, like 20, that can be summed up by two methods: `GetField<T>( int index )` and `GetField<T>( string name )`. It's an implementation that was created before .NET 2.0 introduced generics.

**Comment by Arithmomaniac** [comment]
*facepalm* thanks for pointing that out. (Maybe there could be a table-of-contents sidebar?)

**Comment by JoshClose** [comment]
There is on the top. I just don't each of the FAQ items in the main menu.

**Comment by Arithmomaniac** [comment]
*2x pacepalm* sorry for your time :-)

**Comment by JoshClose** [comment]
Ha, no worries!

**Comment by TrymBeast** [comment]
I would like the IDataReader support because it would improve the use with SqlBulkCopy when the csv file is big. I am trying to import a 6GB file and it takes forever to insert the data in the DataTable.

**Comment by JoshClose** [comment]
I don't understand. Why can't you use SqlBulkCopy right now?

**Comment by TrymBeast** [comment]
@JoshClose I can use it, but it takes too long to process a 6GB file. The DataTable stores all the data in memory and it is swapping to disk. I think that if the CsvReader implemented the IDataReader it would be faster, because the information doesn't need to be all in memory at the same time.

**Comment by JoshClose** [comment]
`CsvReader` does `yield` records. If you don't use `GetRecords` and manually loops the records using `Read`, only a small amount of memory will be used.

```cs
while (csv.Read())
{
    var record = csv.GetRecord<MyType>();
}
```

**Comment by jamesbascle** [comment]
This is correct. If you do things properly you can do end to end streaming
with very little memory usage.

**Comment by nkojuharov** [comment]
Yes, but then writing the data to the database will be extremely slow.  Without IDataReader you have to either read the entire (lots of memory) and use SqlBulkCopy (fast database insert) or yield records (little memory) but then you can't use SqlBulkCopy (so database insert is slow).  

That is, of course, unless you implement IDataReader yourself.
