### ISSUE TITLE
CsvParser does not honor Configuration.TrimFields

### ISSUE THREAD

**Issue by JMerrill** [JoshClose/CsvHelper#417]
It looks like the code that checks the TrimFields property of the configuration is not in CsvParser but rather in CsvReader.

I'm using CsvParser without CsvReader, and setting TrimFields to true in the configuration has no effect.

I'd guess that moving the "look at TrimFields" logic to CsvParser would fix this. Should I try to do that and submit a pull request?

**Comment by JoshClose** [comment]
In 3.0 I'm going to separate the configs out, so it's more apparent where the configurations are valid. Same goes for the writer.

My current thought is that this isn't and shouldn't be the job of the parser. The parser should pull the text out, as is, based on RFC 4180. Anything that isn't RFC 4180 compliant should be behave just like Excel does. That means that everything else needs to be done as a part of the reader.

If you have a really convincing reasoning why this work should happen in the parser instead of the reader, let me know.

**Comment by JMerrill** [comment]
The best reason is "least surprise" -- I built a configuration value with TrimFields set to true and passed it to the parser constructor. There was no way to know that it wouldn't have any impact on the result. (I ended up with some data values with trailing blanks because it did not occur to me to check if the TrimFields value was being ignored.)

If the property were named ReaderTrimFields, or if there were a different configuration class that did not have a TrimFields property that was used when constructing a parser, or if the parser constructor threw an exception when TrimFields was true, I would not have made the mistake I did. (It was of course rather easy to do the trimming myself; I just didn't know that I needed to.)

I think the right solution would be to have (at least) two different configuration classes, and don't have TrimFields in the class that's used to construct the parser. Or at least have the help text displayed for TrimFields (via Intellisense) say "Only for Reader configuration" (or some such).

Depending on how you "separate the configs out" that will likely solve the problem.

**Comment by JoshClose** [comment]
I added interfaces `ICsvParser`, `ICsvReader : ICsvParser`, ICsvSerializer`, `ICsvWriter : ICsvSerializer`.

This allow you to see what is available for the current context you're in.

`CsvReader.Parser.Configuration` will only have parser settings. `CsvReader.Configuration` will have both parser and reader settings, since you can use both there. The same goes for writing.

If you're creating your own and passing it into the parser, you can do this to see the valid options.

```cs
ICsvParserConfiguration config = new CsvConfiguration();
```

This will be in version 3.0.
