### ISSUE TITLE
Quoted fields are not properly escaped when TrimFields is enabled and the quoted field has whitespace outside the quotes

### ISSUE THREAD

**Issue by Zouters** [JoshClose/CsvHelper#422]
If you have `TrimFields` enabled and a field which is quoted and surrounded by whitespace, it does not function correctly. This is a test demonstrating the problem:

            [Test]
            public void TestTrimmingWithQuotedField()
            {
                var csvData = @"
    First,Middle,Last
      Joe ,  ""Billy, Mcgee""   ,  Bob   
    ";
                var stream = new MemoryStream(Encoding.UTF8.GetBytes(csvData));
                using (var reader = new CsvReader(new StreamReader(stream)))
                {
                    reader.Configuration.TrimFields = true;

                    reader.Read();
                    Assert.AreEqual("Joe", reader[0]);
                    Assert.AreEqual("Billy, Mcgee", reader[1]);
                    Assert.AreEqual("Bob", reader[2]);
                }
            }

It fails with message:

    Expected: "Billy, Mcgee"
    But was:  ""Billy"

**Comment by JoshClose** [comment]
This is a malformed CSV file. There shouldn't be any spaces at the beginning or end of the field. Technically, it should think the field isn't quoted because the first char isn't a quote. In these cases, CsvHelper has Excel compatibility. 

Trimming is something that happens in `CsvReader` whereas the fields that are pulled out happen in `CsvParser`. Try doing the same thing with `CsvParser` instead, and you can see how the file is interpreted.

I'd really like to keep that sort of logic out of the parser. I think the parser should be in charge of parsing based on RFC 4180, and then be compatible with Excel for malformed files. The only other extras are changing parsing options like quote/delimiter characters.
