### ISSUE TITLE
Having problem with reading fields with ""

### ISSUE THREAD

**Issue by prabhatdyn** [JoshClose/CsvHelper#465]
Hi,
I am facing a problem while reading the fields from CSV file. The CSV file is having the records like 2000295761|00003|"""10"" EASITAP C/W 1"" BSP OUTLET VJ138||1.00|EA|201.94 
And when i am firing to read the field it return all the string till the end of file in one single record from """10""................
Before this line everything works fine, but when the application reach this line which have """ (3 ") into the field than after that field whatever is there in the file it assume one single field value.  
Can anyone help on this.  Thanks in advance.

Thanks,
Prabhat

**Comment by JoshClose** [comment]
If you open it with Excel, does the same thing happen?

**Comment by prabhatdyn** [comment]
No, in Excel it's open properly without having any issue. 

Thanks,
Prabhat

**Comment by JoshClose** [comment]
Your data is bad. I just tried in Excel and I get 3 fields:
`2000295761`
`3`
`"10" EASITAP C/W 1" BSP OUTLET VJ138,,1.00,EA,201.94`

The issue is, the 3rd field starts with a quote, which means the field is quoted. To escape quotes inside a quoted field, you use 2 quotes. There are 2 quotes after the 1 and no un-escaped quote after that. The field doesn't end until it finds a matching un-escaped quote.
