### ISSUE TITLE
Accessing FieldHeader after GetRecords() causes exception

### ISSUE THREAD

**Issue by j-hudecek** [JoshClose/CsvHelper#495]
I have this code

     var csv = new CsvReader(new StreamReader(filename));
     var data = csv.GetRecords<string[]>();
     var header = csv.FieldHeaders;

and I get an exception "You must call read on the reader before accessing its data. ". GetRecords docs say "Read method should not be used when using this."

**Comment by nebenjamin** [comment]
Having just dealt with a similar issue (#131), the issue is that `GetRecords` returns an `IEnumerable` constructed using the `yield` keyword. `GetRecords` calls `Read` as you iterate over the `IEnumerable`. Since you haven't iterated over the collection, `Read` hasn't been called.

The following should resolve the issue:
``` c#
var csv = new CsvReader(new StreamReader(filename));
var data = csv.GetRecords<string[]>().ToList();
var header = csv.FieldHeaders;
```

It does seem like this is a common enough issue that the `CsvReader`'s constructor may need to be populating the `FieldHeaders` property instead. IMHO, for most people attempting to get `FieldHeaders`, the value of doing so is to check for the presence of specific headers before reading data from the file. I'm assuming that there was a reason for writing it this way, and I'm curious to know what the reason is.

**Comment by JoshClose** [comment]
In 3.0, `Read` and `ReadHeader` are separate. This would allow you do to this.
```cs
csv.Read();
csv.ReadHeader();
var header = csv.FieldHeaders;
var records = csv.GetRecords<MyType>();
```

**Comment by jpcuevas** [comment]
Hi @JoshClose  im try a course in pluralsight  and he is using you nuget pkg but it seem is a previus version  but still i would like to know the change that i need to make it work this is the code until now 

```
using CsvHelper;
using CsvHelper.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Dateprocesor
{
    public class CsvFileProcessor
    {
        public string InputFilePath { get; set; }
        public string OutputFilePath { get; set; }
        public CsvFileProcessor(string inputFilePath, string outputFilePath)
        {
            InputFilePath = inputFilePath;
            OutputFilePath = outputFilePath;
        }

        public void Process()
        {
            //It's now required so people will choose the correct culture for their file. It was previously using a default  CsvReader
            using (StreamReader input = File.OpenText(InputFilePath))
            using(CsvReader csvReader = new CsvReader(input, System.Globalization.CultureInfo.CurrentCulture))
            {
                csvReader.Read();
                IEnumerable<dynamic> records = csvReader.GetRecords<dynamic>();

                csvReader.Configuration.TrimOptions = TrimOptions.Trim;
                csvReader.Configuration.Comment = '@'; // Default is '#'
                csvReader.Configuration.AllowComments = true;

                foreach (var record in records)
                {
                    Console.WriteLine(record.OrderNumber);
                    Console.WriteLine(record.CustomerNumber);
                    Console.WriteLine(record.Description);
                    Console.WriteLine(record.Quantity);
                }
            }
        }
    }
}

```
and this is the csv  file 👍 



> OrderNumber,CustomerNumber,Description,Quantity
> 42, 100001, Shirt, 2
> 43, 200002, Shorts, 1
> @ This is a comment
> 
> 44, 300003, Cap, 5

Please if you can point me in the rigth direction, I would appreciate
