### ISSUE TITLE
Automatic Download

### ISSUE THREAD

**Issue by gregorycooledge** [JoshClose/CsvHelper#503]
Using CSVHelper, on the build machine, the tool is not recognized in references like all the other packages do.  Is there a solution for this other than opening the source on the build machine and force a download.

**Comment by jamesbascle** [comment]
I would suspect you have your references or nuget configured incorrectly. I
know from experience that CsvHelper works fine on build servers, at least
with team city and octopus deploy.

**Comment by jamesbascle** [comment]
It also works fine with azure website auto deploy.

**Comment by gregorycooledge** [comment]
Well that is what we use.  We have a package with about 15 packages and only CSVHelper is causing this problem.   It is also an issue just on a new machine.
Any suggestions?

Thanks
gtc

**Comment by JoshClose** [comment]
It could be the issue with the client profile. I have abandoned the client profile now since moving to .NET Core builds.

Can you try again with the latest build? I'm guessing it'll work.

The issue before was NuGet was incorrectly choosing the wrong version. 

If you still have issues with the latest build, try the latest beta prerelease. If that still has issues, let me know and I'll do what I can to help figure this out.
