### ISSUE TITLE
Prepend long ints with equals sign

### ISSUE THREAD

**Issue by NickAb** [JoshClose/CsvHelper#527]
Similar to `UseExcelLeadingZerosFormatForNumerics` option, there should be an option to prepend numbers with `=` even if the do not start with zero.
This is important for when writing int64 fields, because Excel will convert fields that look like integers into numbers, losing precision.

**Comment by JoshClose** [comment]
Do you think there should be 2 options? 

1. Conditionally add it if there it starts with a 0.
2. Always add it.

Do you see a reason why when the flag is on it wouldn't work to always add an `=`?

Do you think this should be configurable per property instead?

**Comment by NickAb** [comment]
I think it should be either global flag to always add it for every `long` field or configurable per property.

Making it configurable per property seems to be most flexible.

**Comment by jamesbascle** [comment]
Would this kind of thing be better served by a custom type converter? I'm a
bit confused why it's being proposed as a core library configuration.  Is
this soley for excel support?

**Comment by JoshClose** [comment]
Essentially, it's an Excel formula. When Excel sees that in a CSV file, it handles it differently.

In version 3, I want to change how this works. Have a way for it to work whenever you want it to and not have to look for specific types. There is the case of 0's, there is the case for longs, and I'm sure there will be a bunch more cases where someone wants the `=` prepended.

This solely for Excel support, but I've committed to some degree of Excel compatibility. If data is malformed, I want to behave how Excel would. 

@jamesbascle What do you have in mind as a different way to support this? Honestly, I'd love to not have it in as core functionality. Right now for reading it's in the parser because I want it to parse a field like `=00123` as `00123`. I could probably be convinced that the parser should just parse as a CSV field, and let the reader handle things. What sort of custom converter would do this? It would need to work with many different types. short, int, long, etc.

**Comment by jamesbascle** [comment]
I see. Its been about 3-4 years since I've used excel much at all.  I get
the motivation now - that makes sense.

I can think of a number of ways to accomplish it without invading the core
configuration, including a few extension methods that apply the various
numerical types' excel number converter to the property map.  Essentially
partially applying the TypeConvert method on the property maps.

I can also see the desire on the users' part to make it a 1 stop config
change, but that pushes performance cost onto others, and pushes more
configuration into the core library functionalities.

Maybe a compromise could be made.  A specialized CsvClassMap<T> abstract
subclass, maybe ExcelCsvClassMap<T>, that would automatically apply the
aforementioned TypeConvert wrapping call to the properties?  I could even
see a CsvHelper.Excel package being put together that provides all kinds of
tools for working with excel files specifically.  I would think that if it
were set up correctly, it could handle all the weirdness of excel files
that I've heard about completely outside of the core library.

At my last job, I actually wrote a type safe wrapper around the entirety of
the Google AdWords reporting API using CsvHelper as the parsing engine,
heavily (ab)using type converters, dynamically generating class maps, and
dynamically compiling CsvModels at runtime from a an arbitrary number of
interfaces - so you can do some pretty complicated things just by
configuring your class maps and type converters properly.  In comparison,
the task of adding an = to the front of some number fields seems pretty
simple.

Now, don't take this as my opposition to a core configuration value either,
it just seems highly specific to be in a core configuration.  However,
there is precedent with the ExcelLeadingZeros and the HasExcelSeperator
options.  The leading 0 bit could obviously be added to the aforementioned
excel type converter and configurable via aforementioned property map
extension method. The separator bit seems more complicated, and I don't
really understand its inner workings at all, so I can't comment on it at
the moment.

Okay that got pretty rambly, I'm Really just throwing ideas out at the
moment, interested to hear other's thoughts on what i've said, or other
options.

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#7
