### ISSUE TITLE
Support fixed width parsing

### ISSUE THREAD

**Issue by roryprimrose** [JoshClose/CsvHelper#54]
I had a developer yesterday ask me how to easily parse a fixed width formatted file. I thought this library could work with a little bit of customisation of the CsvParser. Perhaps fixed width support could be supported by allowing definition of a ColumnWidth on the CsvField attribute (and obviously ignoring the comma delimiter).

**Comment by JoshClose** [comment]
I'm thinking I may add this to version 3.0.

**Comment by dmitry-azaraev** [comment]
@JoshClose I'm add ability of writing fixed-length fields, implementation now https://github.com/dmitry-azaraev/CsvHelper/tree/feature/writing-fixed-length-records .

It is actually do next things:
- Allow use empty delimeter. (Alternatively it is enough to make own CsvSerializer and do not emit delimeters).
- (Not directly related): Constants uses type converters. Current versions falls on Map().Constant(123). I'm fix it to always invoke type converters even for constants.
- Allow configure CsvPropertyMap Width, Align and AlignErrorMode for writing fixed-length fields.
- Added some tests about using width, align and error mode.

Basic idea of usage is:
```csharp
    // configure 
    configuration.Delimiter = "";
    configuration.QuoteNoFields = true;
    configuration.HasHeaderRecord = false;

    // in map, define mappings
    Map(m => m.Id).Width(5);
    // or 
    Map(m => m.Id).Width(5, CsvAlign.Right);  // will pad spaces from left
    // or
    Map(m => m.Id).Width(5, CsvAlign.Right, CsvAlignErrorMode.Throw);  // will throw if field is not fit in space
```

Even while it is only supports writing, i'm found that it is simpler keep using one CsvHelper because when i'm write files, i'm use same fluent mapping syntax, reuse formats / etc. Do you like something like this?

And can i'm (we) count to have similar functionality in nearest future. I.e. what i'm should do to have PR been accepted?

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#2

**Comment by niemyjski** [comment]
+1
