### ISSUE TITLE
Writing with underlying MemoryStream does not work

### ISSUE THREAD

**Issue by matteo-mosca** [JoshClose/CsvHelper#577]
I am trying to save an IEnumerable content. If the underlying stream passed to the StreamWriter is a FileStream everything works correctly.

If I change it to a MemoryStream the stream is always empty (0 length) after the process.

I need to use a MemoryStream in a WebAPI scenario where I do not need to create a file but just get the array of bytes for a download.

**Comment by JoshClose** [comment]
Can you give an example of this failing? My guess is you need to flush the `StreamWriter` after you've written your CSV data.

**Comment by jamesbascle** [comment]
You need to set your MemoryStream's position to 0 after populating it
initially.

**Comment by matteo-mosca** [comment]
The correct thing was the need to flush it. The "position" suggestion had nothing to do with it, as the stream was empty.

Still I think that since I'm passing the stream to the CsvWriter (through the StreamWriter) it should be CsvWriter job to ensure data is flushed. Just my thought.

Thanks.

**Comment by JoshClose** [comment]
The `CsvWriter` take in a `TextReader`, not a `StreamWriter`. It has no clue what implementation it has. This makes it more flexible. Normally if you wrap your code in `using` blocks, it gets flushed automatically. In the case of needing to write to a stream so it can get read again, you won't be doing that. There is always `StreamWriter.AutoFlush` if you want, but be careful with that. If you're stream is over the wire, it's slow things down significantly.

**Comment by jamesbascle** [comment]
I meant that, after writing to it, you need to set position to 0 before
using it to write to something else or read from it.  I could be wrong
though...

On Sep 13, 2016 3:56 PM, "Matteo Marco Mosca" <notifications@github.com>
wrote:

The correct thing was the need to flush it. The "position" suggestion had
nothing to do with it, as the stream was empty.

Still I think that since I'm passing the stream to the CsvWriter (through
the StreamWriter) it should be CsvWriter job to ensure data is flushed.
Just my thought.

Thanks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/JoshClose/CsvHelper/issues/577#issuecomment-246803817>,
or mute the thread

**Comment by robertmclaws** [comment]
So, I'm having a similar issue in a Windows 10 app. The following code freezes after writing 64kb of data with no exception thrown:

```cs
        using (var stream = await KnownFolders.DocumentsLibrary.OpenStreamForWriteAsync("Lead.csv", CreationCollisionOption.GenerateUniqueName))
        {
            using (var writer = new StreamWriter(stream))
            {
                var csv = new CsvWriter(writer);
                csv.WriteRecords(LeadRecords);
            }
            await stream.FlushAsync();
        }
```
`LeadRecords` is an `ObservableCollection<dynamic>` that was populated from a CsvRead.

Setting the buffer size appears to have no effect, and writing each record individually and auto-flushing does not work at all. Setting the stream to AutoFlush lets me write 7 more records before it craps out vs not auto-flushing.

It appears to be related to the fact that CsvWriterTests has the unit test for writing ExpandoObjects ignored.

As an aside, can you fix the documentation so that it actually shows how the code prefers to create the TextReader/TextWriter instance to use? All of the samples just show an instance already being passed in, and none of your tests appear write to disk.

Thanks!

**Comment by JoshClose** [comment]
Can you try doing a `writer.Flush();` after you write the records?

I'm going to add a lot of documentation when version 3 is released.

**Comment by JoshClose** [comment]
Also, `ExpandoObject` is supported in version 3 which is in beta right now. You can get the beta from NuGet.

**Comment by robertmclaws** [comment]
I tried a `writer.Flush()`, but the code isn't even getting to that line before the app freezes. I'm currently using 3.0 Beta 6 from NuGet.

**Comment by JoshClose** [comment]
OK. I'll setup an example to try and reproduce on a windows 10 app.

**Comment by robertmclaws** [comment]
I have a unit test running right now with the actual file. And it hasn't failed yet... so I'm thinking, maybe the code is just really, really slow.

Wouldn't it be quicker to use a StringBuilder to build up the output and then only write it when your totally done?

**Comment by JoshClose** [comment]
The entire file into a StringBuilder? That would chew up a lot of memory and possibly spill over to disk. The `StreamWriter` should buffer until full, then flush itself to the `Stream`.

I'm guessing it has to do with writing a dynamic object. Try creating an actual class for the same data and see if that speeds it up. There is probably a lot of optimization that could be done around dynamic types.

**Comment by robertmclaws** [comment]
I was researching ExpandoObject a bit. I think it might be easier if your code just [cast it to a Dictionary](http://stackoverflow.com/a/14383933/403765) and cycled through that, vs using Reflection.

**Comment by JoshClose** [comment]
Would you be able to create an example Windows 10 app the reproduces the issue that I can test with? I'll take a look at it tonight.

**Comment by robertmclaws** [comment]
Yep. Can you send me your e-mail address, please? I'm going to use real data and I don't want to post it publicly.

**Comment by robertmclaws** [comment]
Question: Why are you trying to write the header for every record on a Dynamic object? https://github.com/robertmclaws/CsvHelper/blob/master/src/CsvHelper/CsvWriter.cs#L472-L503

**Comment by JoshClose** [comment]
narshe on Google's email service.

I'll answer the other question when I get to a computer

**Comment by robertmclaws** [comment]
You can delete your e-mail comment now. I have an e-mail in progress :)

**Comment by JoshClose** [comment]
So, the reason it has to check about writing the header every loop is because it's not able to write it ahead of time. The type of a `dynamic` is `object`. There's no way to get the real type of the items in the list until you read the first record. There is also the possibility that there could be multiple types in the list, but the header only gets written for the first item's type.

**Comment by robertmclaws** [comment]
So, I'm looking at the code now, and I'm testing a way that you can write it ahead of time. But it begs another question: it appears that this code would be slightly easier if the method was generic. Is there a reason it isn't? If I could make this work faster, but the IEnumerable passed in had to be generic, and it broke the existing interface for some, would that be OK?

**Comment by JoshClose** [comment]
This is a major version bump because I've broke lots of things already. :)

It used to be a generic but there ended up not being a use for it, so it was removed. I don't see any harm in adding it back.

**Comment by JoshClose** [comment]
For others, I worked with @robertmclaws on a solution for this issue. 

The problem was the Expression code that is generated by `Microsoft.CSharp.RuntimeBinder.Binder.GetMember` to get the property values out of a dynamic was doing a check `RuntimeOps.ExpandoCheckVersion` to see if the interal `Class` property of type `ExpandoClass` of the expressions expando type matched that of the expando trying to be used. Even though they had the same properties, the check was sometimes failing. I wasn't able to figure out why, and it seemed like a bug to me.

The fix was to handle ExpandoObject separate from other `IDynamicMetaObjectProvider` types. I tried a different implementation of `IDynamicMetaObjectProvider` [Clay](http://clay.codeplex.com) which worked just fine. 

Thanks to @robertmclaws for his help!
