### ISSUE TITLE
Exception reading headers in 3.0.0-beta7

### ISSUE THREAD

**Issue by marcwmiller** [JoshClose/CsvHelper#584]
The following worked in 3.0.0-beta6 without error/exception. Latest version is throwing exception CsvHelper.CsvReaderException - No header record was found.  Bug or improper implementation that is breaking in 3.0.0-beta7?

            var headers = new string[] { "header1", "header2" };
            var csv = $"{headers[0]},{headers[1]}{Environment.NewLine}value1,value2";

            using (var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(csv)))
            {
                stream.Position = 0;

                using (var streamReader = new StreamReader(stream))
                {
                    using (var csvReader = new CsvReader(streamReader))
                    {
                        // default but explicitly setting
                        csvReader.Configuration.HasHeaderRecord = true;
                        csvReader.ReadHeader();
                        var fieldHeaders = csvReader.FieldHeaders;
                    }
                }
            }

**Comment by JoshClose** [comment]
Yes, there was a breaking change. I should find a place to post all the changes.

You need to call `Read` now to read the row. `ReadHeader` doesn't automatically do it for you anymore. 

There were a few reasons for this but the main one is to allow for reading of multiple headers. If there are headers on the first row, then records for that type, then another header, and records for another type, you can now read through that file.

The other reason is consistency. `Read` will progress you to the next record. You can then use all the other methods to do things with the current record. `ReadHeader`, `GetField`, `GetRecord`, etc. It allows you to be specific about what you're doing, and hopefully cause less confusing; although there will be a little at first since it's a change from how it previously worked.

Using `GetRecord<T>` will automatically call `ReadHeader` and `Read` if you have `HasHeaderRecord` on and you haven't read yet, but you can still do it manually. I did this to make reading a full record as easy as possible. `GetRecords<T>` will obviously do everything for you.

**Comment by marcwmiller** [comment]
Cool - thanks for explanation of change.

**Comment by JoshClose** [comment]
I should put up a beta change log that lists all the breaking changes.
