### ISSUE TITLE
Infer default Delimiter from CultureInfo

### ISSUE THREAD

**Issue by Halofreak1990** [JoshClose/CsvHelper#610]
At present, the default Delimiter is always a comma. However, not all locales use this symbol as separator in CSV files; for example, in the Netherlands we use a semicolon. It would be better if the default Delimiter were inferred from the CultureInfo.TextInfo.ListSeparator property.

**Comment by JoshClose** [comment]
This is in 3.0

**Comment by novanettor** [comment]
Doesn't seem to work for me. I am using 6.0.0, and I have to set Configuration.Separator = CultureInfo.CurrentCulture.TextInfo.ListSeparator, otherwise it will be comma regardless.

**Comment by JoshClose** [comment]
Yes, you have to specifically set it. The file type is CSV `comma separated values`, so I took the hard stance that it's going to be commas unless you specifically change it.

**Comment by novanettor** [comment]
Hi Josh

That's fair enough, however:

This issue (#610) is specifically about inferring the default value for the delimiter from culture info. So your original comment:
   "This is in 3.0"
is misleading, because it isn't.

Anyway, just to argue the case a little: I know, of course what CSV stands for. It's still true that for cultures that use comma as a decimal delimiter (including much or most of Europe), the default delimiter by convention is semicolon - for obvious reasons. Any user in any of these countries who saves an Excel spreadsheet as CSV will get a semicolon-delimited file, because Excel is culture-aware.

What is most important then - the literal meaning of the abbreviation (probably originating in the US or UK decades ago), or the reality for millions of users?

**Comment by JoshClose** [comment]
I see your point... I'm going to try and find why I switched it. I honestly forget the reason now. ;)

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper/issues/718

**Comment by JoshClose** [comment]
I'll have to think about this. I'll need to update all my tests to use `CultureInfo.CurrentCulture.TextInfo.ListSeparator` or change the config of all the tests.

I really don't want writing to output something other than a comma by default either. CSV isn't what Excel reads and writes, it just has the capability of importing and exporting to that type. I think what happened was they didn't use escaping originally, so if you had numbers, you might run into this issue. I'd much rather have something that specifically does CSV to do it correctly by default. I honestly don't even see this as a culture issue. It's an issue of Excel not adhering to the standard. If you get CSV files from other things, do they use a culture specific list separator instead of a comma? I do want this library to just work out of the box, so I'm inclined to change it, but it really sucks that it won't be following the CSV format by default.

**Comment by JoshClose** [comment]
I added a feature #918 for this. Continue the discussion over there.
