### ISSUE TITLE
ReferenceMap is not ignored

### ISSUE THREAD

**Issue by vk5880** [JoshClose/CsvHelper#613]
public sealed class ReportMapping : CsvClassMap<Report>
    {
        public ReportMapping()
        {
            AutoMap();
            Map(m => m.SomeId).Ignore();
            Map(e => e.SomeReference).Ignore();
       }
    }
is not respected and leads to exceptions related to SomeId is property of SomeReference type.
can be solved as

    public sealed class ReportMapping : CsvClassMap<Report>
    {
        public ReportMapping()
        {
            AutoMap(true);
            Map(m => m.SomeId).Ignore();
       }
    }

**Comment by JoshClose** [comment]
How things work under the hood is everything builds up to a list of properties that are mapped. The property could be `A` or `A.B` or `A.B.C`. When you auto map, it goes through the entire class hierarchy and will create a property map for every property. 

When you ignore a reference, it really doesn't do anything because it wasn't mapped before anyways. References like that are held in a reference map, which just contains property maps, instead of being a property map itself.

Now, maybe that would be an interesting feature to go through the list of currently mapped properties all the way down the tree and remove them in this case... but that seems odd because you're essentially undoing what you just did.

Try debugging and after you create the map, take a look at the structure.

I'll have to think about a good way to do something like that. The point of exposing `AutoMap` in the mapping file was to allow you to do everything, and make a couple changes. This is a scenario I didn't think of yet.

**Comment by vk5880** [comment]
I've debugged a lot, and I was quite surprised that Report.SomeReference.SomeId is included in mapping and the issue is not with Report.SomeId ignore mapping. It was hard to believe as error message contained error related to SomeId property and I thougth it is an issue with Ingore. I think that it will be good to have more details in exception in such case. Thanks.

**Comment by JoshClose** [comment]
I'm out of town for a week with no access to a computer, so I will respond to this more when I return.

**Comment by JoshClose** [comment]
Having it remove all the things that were added doesn't make sense I don't think based on my previous comments.

I added this comment to the method so it's more clear what will be happening.

```cs
/// If this property has already been mapped as a reference
/// property, either by a class map, or by automapping, calling
/// this method will not ingore all the child properties down the
/// tree that have already been mapped.
```
