### ISSUE TITLE
Whitespace-only differences in delimiter character breaks dynamic quoting

### ISSUE THREAD

**Issue by agc93** [JoshClose/CsvHelper#628]
Example: When using `CsvWriter`, setting `CsvWriter.Configuration.Delimiter` to `",\t"` (i.e. comma followed by tab) means that fields will only be quoted when they include exactly that value. In this example, this means fields with commas won't be quoted unless they are followed by a tab character. 

Just a question/thought, could the behaviour be adjusted to quote fields containing the delimiter character **ignoring whitespace**?

Adding a tab character fixes a lot of problems with Excel's (infuriating) auto-formatting, but breaks the "auto-quoting" that `CsvWriter` does.

**Comment by jamesbascle** [comment]
I know Josh has mentioned creating some kind excel extensions library in
the future possibly with 3.0 due to the myriad ways in which Excel likes to
behave strangely, and the increasingly complex behaviors that need to be
added to the parsers and writers.

In lieu of that, however, it would seem to me that just quoting all fields
ought to work just as well.

On Jan 18, 2017 4:07 AM, "Alistair Chapman" <notifications@github.com>
wrote:

Example: When using CsvWriter, setting CsvWriter.Configuration.Delimiter to
",\t" (i.e. comma followed by tab) means that fields will only be quoted
when they include exactly that value. In this example, this means fields
with commas won't be quoted unless they are followed by a tab character.

Just a question/thought, could the behaviour be adjusted to quote fields
containing the delimiter character *ignoring whitespace*?

Adding a tab character fixes a lot of problems with Excel's (infuriating)
auto-formatting, but breaks the "auto-quoting" that CsvWriter does.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JoshClose/CsvHelper/issues/628>, or mute the thread

**Comment by agc93** [comment]
Unfortunately the target system for the CSV file is a bit obstinate and won't accept quotes on all fields, so can't just quote everything. 

The Excel part was mostly included as a context, since there might be other scenarios where tabbed (or spaced) delimiters could be used as well.

**Comment by JoshClose** [comment]
What about `Configuration.QuoteRequiredChars`?

**Comment by agc93** [comment]
@JoshClose Looks to me like [that property](https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvConfiguration.cs#L189) is read-only?

**Comment by agc93** [comment]
@JoshClose I can't seem to add new entries to that array property?

![image](https://cloud.githubusercontent.com/assets/1369269/22096194/bbdf191a-de65-11e6-87d2-b2359fbce71b.png)

Am I doing something wrong here?

**Comment by JoshClose** [comment]
That's because it's an array. I should make the property settable. For now you could create a class that inherits `CsvConfiguration` and override that property and pass that into your writer.

**Comment by jamesbascle** [comment]
I agree with that, FWIW.  I know a number of settings from the configuration are copied into the writer/reader/parser, but I don't think everything is.  Maybe it would be easiest to make a deep clone of the configuration object once it's set, or use the values off the configuration object directly.

It seems that letting certain settings be mutable mid-write/read and others not be is somewhat problematic and unintuitive.  Thoughts?

**Comment by JoshClose** [comment]
I the method `BuildRequiredQuoteChars` a public property of type `Func<char[]>` so it can be easily set to something else and added to. This method gets called any time the delimiter is set. This is also the reason the `QuoteRequiredChars` field is readonly.
