### ISSUE TITLE
Cannot use CsvReader in ASP.Net Core due to security transparency.

### ISSUE THREAD

**Issue by stephendrew** [JoshClose/CsvHelper#663]
Hi,

I get an error when trying to use `CsvReader.GetRecord<T>` in .NET Standard 1.4:

```csharp
var config = new CsvConfiguration
{
	HasHeaderRecord = true
};

var reader = new CsvReader(streamReader, config);

var list = new List<Dummy>();
while (reader.Read())
{
	var item = reader.GetRecord<Dummy>();
	list.Add(item);
}
```

Error details:

```
MethodAccessException: Attempt by security transparent method 'CsvHelper.ReflectionHelper.CreateInstanceDelegate(System.Type, System.Object[])' to access security critical method 'System.Reflection.TypeExtensions.GetConstructor(System.Type, System.Type[])' failed.

Assembly 'CsvHelper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
```

Am I doing something wrong?

Thanks.

**Comment by JoshClose** [comment]
What version of CsvHelper are you using?

**Comment by stephendrew** [comment]
3.0.0-beta8

**Comment by JoshClose** [comment]
I tried to reproduce this and wasn't able to. I created a netcore1.1 console project that references a netstandard1.4 library project. The library references CsvHelper 3.0.0-beta8. I was able to read records without any exception.

Can you give me some details on project setup? It's a netstandard1.4 project? Do you have any special security settings in place?

**Comment by stephendrew** [comment]
CsvHelper is being used inside a .NET Standard 1.4 class library, which is being referenced by a .NET 4.6.2 ASP.Net Core web application.  The CSV parsing is taking place in a constructor of a singleton object in the ASP.Net Core dependency injection (probably not great, I will move it to something a little more sensible).

I haven't done anything special around security...  thanks for investigating!

**Comment by JoshClose** [comment]
Are you able to create a self contained project that reproduces the issue and put it somewhere I can download?

**Comment by stephendrew** [comment]
Here, I hope you can access this: https://www.dropbox.com/s/dzzo1y9muvrik95/CsvHelperRepro.Lib.zip?dl=0

**Comment by zigna-jjn** [comment]
Any news garding this issue? I've just encountered the same bug in a 4.6 project.

**Comment by zigna-jjn** [comment]
Ok, fixed it by downgrading to the stable version.

**Comment by JoshClose** [comment]
I'm trying to figure out if there is something I can do to the netstandard project to work. If all else fails, I can just include a .NET 4.0 build also. That might not be a bad idea for the time being.

**Comment by JoshClose** [comment]
This is fixed. I removed `AllowPartiallyTrustedCallers`. MS said it doesn't really mean anything going forward, and it shouldn't be using that for security anyways.

Release 3.0.0-chi02 is out. I realized that NuGet for dash releases like beta sort alphabetically. That means release 8 is the latest, even though release 10 is out. I went to `chi` since `c` is the next letter in the english alphabet. Gamma is actually the 3rd letter in the Greek alphabet and Chi is 3rd from the last. Oh well.

**Comment by farzinflybits** [comment]
Hi Josh,

I'm using version 2.16.3 in an AWS lambda function (.net core 1.0) 
this is the code sbippet:

                            for (int i = 0; i < columns; i++)
                            {
                                ((IDictionary<String, Object>)record).Add(reader.GetName(i), reader.GetValue(i) != System.DBNull.Value ? reader.GetValue(i).ToString() : "");
                            }
                            csvHelper.WriteRecord(record);
I get the following error on this line  csvHelper.WriteRecord(record);

Types that inherit IEnumerable cannot be auto mapped. 
Did you accidentally call GetRecord or WriteRecord which 													 acts on a single record instead of calling GetRecords or 													 WriteRecords which acts on a list of records?

this also throws the same exception:

                        records.Add(record);
                        csvHelper.WriteRecords(records);

I would appreciate it if you could let me know if it's because of the version I'm using which is not compatible with .net core 1.0 or something else.

Best regards,
Farzin

**Comment by JoshClose** [comment]
It looks like you're trying to write an `IDictionary<string, object>` as your record.

**Comment by gtaylor44** [comment]
3.0.0-beta8 looks to be the last version using .netstandard <= 1.3

Now targeting .netstandard >= 2.0 

What is the reason for this?

**Comment by JoshClose** [comment]
2.0 has more features. I figure the people that are able to update to dotnet core should be able to update to 2.0 also.

**Comment by gtaylor44** [comment]
Corporates don't like updating.

**Comment by JoshClose** [comment]
Are you currently using the beta?
