### ISSUE TITLE
Add ConvertUsing to writer

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#698]
The names will need to change. There will need to be a separate one for reading and writing.

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper/commit/e40570fb314af1af1bf2b598695c6e0bff234594

**Comment by StefanBertels** [comment]
Thanks for this feature (related comment: #679).

Just a comment regarding lib design: I found it not very clear that CsvPropertyMap sometimes related to a property and sometimes to the whole record (i.e. whole record is always accessible).

```Map(m => m.MyColumName).ConvertUsing(...)``` 

I expected that ConvertUsing would need only string to typeof(MyColumnName) and vice versa. I appreciate the flexibility that I can e.g. combine columns or split properties to different columns but maybe this should be separated?

After looking into the code the reason behind seems that you have a Field Name collection so you can't see at compile time whether there is a member (name) or not (or maybe more than one). Maybe would be better to make this separate (sub) types: 

classmap.Map(m => m.ColumnName) could return something like a ColumnMapping which is different to something like RowMapping (similar features to current PropertyMap)...

However: I now use this extension as workaround:

```
    public static CsvPropertyMap<TClass, T> ConvertPropertyUsing<TClass, T>(this CsvPropertyMap<TClass, T> map, Func<string, T> readExpression, Func<T, string> writeExpression)
    {
        return map
                .ConvertUsing(row => readExpression(row.GetField(map.Data.Names.First())))
                .ConvertUsing(obj => writeExpression((T)(map.Data.Member as PropertyInfo).GetValue(obj)));
    }
```

It's compact but a bit hacky. TypeConverters solution (compare #679) was more boilerplate but better code.

Anyway thanks for this ConvertUsing-for-write feature.

**Comment by JoshClose** [comment]
I guess I don't see the issue here... Why is it bad to give the user the whole row? The point was to allow the user to be able to do whatever they want with the current row to be able to make the property.

>Just a comment regarding lib design: I found it not very clear that CsvPropertyMap sometimes related to a property and sometimes to the whole record (i.e. whole record is always accessible).

It's always relating to a property. It just allows you to use the whole row to create the property.

**Comment by StefanBertels** [comment]
Hi Josh,

it is not bad to give the user the row and I understand that the user needs the row for e.g. combining fields.

In fact I meant "related to a csv field". Some code:

`Map(m => m.MyColumnName).Name("MyColumnName").ConvertUsing(row => row.GetField("MyColumnName")`

I'm aware that `Name()` is not neccessary here because it is parsed out of the expression parameter to `Map()`. But I care about ConvertUsing having to make some complicated lookup in CsvPropertyMapData to get MyColumnName or having duplicate code ("MyColumnName") or having different styles of implicit/explicit field name settings.

My (main) use case for anything with TypeConversion/ConvertUsing is to work on single csv fields defined implicitly by `Map()` or explicitly `Map().Name()`. Therefore my extension.

Some typical code:

```
public Map()
            {
                Map(m => m.FileType);
                Map(m => m.ProcessId);
                Map(m => m.LastUpdate)
                        .ConvertPropertyUsing(
                              DateTimeExtensions.ParseNullableLocalDateOrDateTime,
                              DateTimeExtensions.FormatLocalDateTimeIso);
                Map(m => m.Category);
                Map(m => m.Revision);
            }
```

CsvHelper does a great job and mapping simple column types like int, int?, string etc. works with minimal code. But I have some more types where I need conversion expressions between Property (type) and csv field value (string).

Anyway, I have my workaround which works fine for me.
