### ISSUE TITLE
Parse exceptions thrown from CsvReader.GetField<T>() don't get enriched by ExceptionHelper.AddExceptionDataMessage()

### ISSUE THREAD

**Issue by toddweb** [JoshClose/CsvHelper#706]
It would be great to have a more consistent experience as GetRecord<T>() does enrich exceptions.

**Comment by JoshClose** [comment]
I just added a change where `CsvReader`, `CsvParser`, and `FieldReader` all share a `ReadingContext` that is the state of the application. Likewise, `CsvWriter`, and `CsvSerializer` all share a `WritingContext`. Now when any exception is thrown, there is a `ReadingContext` and `WritingContext` on the exception object that contains the current state of the application. This will have a lot more information than before. The only exceptions that won't have that are configuration exceptions, since reading/writing more than likely hasn't started yet.

I think this should cover your issue, but let me know if there is anything else. This will be in the next 3.0 pre-release on NuGet; more than likely today.

**Comment by toddweb** [comment]
Thanks Josh ... what is the 3.0 release roadmap (i.e. when is it likely to be in full release and out of beta)?

**Comment by JoshClose** [comment]
Last September. ;) I keep finding things that are breaking changes that I want to do. I've also decided to move a few things out into a contrib project and not be a part of the main library.

Hopefully in the next couple of months it'll be done. The pre-release is very stable, as in it has a lot of unit tests around it and should work well. It does run the risk of having breaking changes until the release though.

**Comment by JoshClose** [comment]
I'm spending pretty much all of my free time to finish it up. This is my main focus until it's complete.
