### ISSUE TITLE
Attributes are supported or not?

### ISSUE THREAD

**Issue by mabead** [JoshClose/CsvHelper#740]
According to the documentation [here](https://github.com/JoshClose/CsvHelper/wiki/Custom-TypeConverter), attributes can be used to specify type converters. But according to [another page](https://github.com/JoshClose/CsvHelper/issues/163), attributes can't be used.

Which one is right?  If attributes are not supported, please update the documentation to remove the example that shows how to use the attributes.

**Comment by jamesbascle** [comment]
I believe they are no longer supported.  I think they were removed during
early 2.x

On Aug 28, 2017 10:34 AM, "Maxime Beaudry" <notifications@github.com> wrote:

According to the documentation here
<https://github.com/JoshClose/CsvHelper/wiki/Custom-TypeConverter>,
attributes can be used to specify type converters. But according to another
page <https://github.com/JoshClose/CsvHelper/issues/163>, attributes can't
be used.

Which one is right? If attributes are not supported, please update the
documentation to remove the example that shows how to use the attributes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JoshClose/CsvHelper/issues/740>, or mute the thread

**Comment by JoshClose** [comment]
No, they are not supported. I need to remove the wiki. It's very out of date and not maintained. This is the documentation that should be used. http://joshclose.github.io/CsvHelper/
