### ISSUE TITLE
ITypeConverter

### ISSUE THREAD

**Issue by neslekkim** [JoshClose/CsvHelper#759]
I have done like #643 and created an typeconverter, the idea here is that I don't want the default value in the csv file if the enum have no value.

```
public enum MyType
{
    Unknown = 0,
    P,
    M,
}

public class MyTypeConverter : ITypeConverter
{
    public string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
    {
        if ((MyType)value == MyType.Unknown)
            return "";
        return value.ToString();
    }

    public object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
    {
        throw new NotImplementedException();
    }
}

using (TextWriter textWriter = new StreamWriter("outputfile.csv")))
using (var csvOut = new CsvWriter(textWriter))
{
    csvOut.Configuration.Delimiter = ";";
    var options = new TypeConverterOptions { Formats = new string[] { "d" } };
    csvOut.Configuration.TypeConverterOptionsFactory.AddOptions<DateTime>(options);
    csvOut.Configuration.TypeConverterOptionsFactory.AddOptions<DateTime?>(options);
    var myTypeConverter = new MyTypeConverter();
    csvOut.Configuration.TypeConverterFactory.AddConverter<MyType>(myTypeConverter);

    csvOut.WriteRecords(totalt);
}

```
But, my converter is never called?

**Comment by JoshClose** [comment]
So here is a strange issue with moving the `TypeConverterFactory` into the `Configuration`. There is no configuration accessible inside `ClassMap`. If you end up using auto mapping, any type converter changes in the configuration aren't used, because the mapping doesn't have access to it, and instead uses a global instance `TypeConverterFactory.Current`.

To solve your problem, I think you just need to change the `TypeConverterFactory.Current` instead.

I think this is a problem and is quite confusing though. I will have to think this over and see what I can do. I may have to have the `ClassMap` require a `Configuration`. This may work out OK because when doing `csv.Configuration.RegisterClassMap<TMap>()`, the reader/writer will have an instance of the `Configuration` to pass in. Auto mapping would be trickier, but that could require a config also. The only place I see some weirdness would be calling `AutoMap()` from inside a `ClassMap`.

**Comment by JoshClose** [comment]
`Current` is actually used in
- NullableConverter
- ClassMap
- MemberMap`1
- ParameterMap

**Comment by JoshClose** [comment]
This kinds sucks.

```cs
public class MyClassMap : ClassMap<MyClass>
{
    public MyClassMap( Configuration config ) : base( config )
    {
        ...
    }
}
```

I really don't like having to require the user to pass a configuration in .

**Comment by neslekkim** [comment]
I'm not using a ClassMap in this case, when possible I want to avoid them in this small project, but I can see the need in other projects though.
I didn't know there was an .Current method, maybe it would work for my, will try tomorrow.

**Comment by JoshClose** [comment]
I actually found a way to remove `TypeConverterFactory.Current` without requiring `Configuration` to be passed in everywhere.  f9e5f10ba71a4d838619d718f01034e53146b92b
