### ISSUE TITLE
Support for .Net Standard

### ISSUE THREAD

**Issue by ameem85** [JoshClose/CsvHelper#836]
The current version i.e 5.0.0.1 does not support .Net Standard
Error message:
Installing CsvHelper 5.0.0.1.
Package CsvHelper 5.0.0.1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package CsvHelper 5.0.0.1 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by JoshClose** [comment]
Is there a reason you can't upgrade to netstandard2.0 or core 2.0?

**Comment by ameem85** [comment]
Never mind, I was able to upgrade to 2.0 and able to install the nuget package. Thanks

**Comment by jamesbascle** [comment]
Also, for future reference, if someone needs an old version of .net to run,
I think the only change that would need to be made is a version flag around
the serializable attributes.  That should allow targeting of 1.3 if IIRC.

On Nov 7, 2017 3:01 PM, "Josh Close" <notifications@github.com> wrote:

Closed #836 <https://github.com/JoshClose/CsvHelper/issues/836>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JoshClose/CsvHelper/issues/836#event-1330485908>, or mute
the thread

**Comment by JoshClose** [comment]
It could be limiting in other areas in the future though. Currently my thought is anyone that has been able to upgrade to .NET Core last year will also be able to update to .NET 2.0 this year. I could probably do it for now and remove it later if need be.

**Comment by JoshClose** [comment]
I just tried and there is a bunch of stuff in reflection that is different. Unless I find a real compelling reason, I'm not going to add it. So far everyone has been able to upgrade.
