### ISSUE TITLE
How get columns dynamically

### ISSUE THREAD

**Issue by felipeoriani** [JoshClose/CsvHelper#884]
Hi, 

A part of our project here need to read CSVs files. It is a dynamic part so we can not have a class to use as a Modal. So, given a CSV file, we need to read what are the columns to persist the columns format on our database to read on the future processes. So, I would like to implement something like this:
```

var reader = new CsvReader(csv, new Configuration()
{
   HasHeaderRecord = true, Delimiter = ";"
});

while (reader.Read())
{
    int totalColumns = ??? // how?
    for (int columnIndex= 0; columnIndex< columnIndex; column++)
   {
      var columnName = reader.GetColumnName(); // how?
      var columnType = reader.GetColumnType(columnIndex); // how?
      var value = reader[columnIndex]; // that's fine
   }
}

```
I would like to know, how can I get the total of columns on the CSVReader, and inside the loop, be able to get the column name and type? Is it possible?

Thank you.

**Comment by JoshClose** [comment]
You can view the current record using `reader.Context.Record`. On the first read, that record will be the header. You can view it at any time using `reader.Context.HeaderRecord` after you've read it. There is no way to determine a type since CSV files are all strings. If these are columns in a database, you could match the header with the db column and figure the type that way I guess.

```cs
reader.Read();
// This will things up so values show up in Context.HeaderRecord and allow you to use GetField( string name ).
reader.ReadHeader();
while (reader.Read())
{
    ...
}
```
