### ISSUE TITLE
Any planned support for fixed width files?

### ISSUE THREAD

**Issue by reloaded** [JoshClose/CsvHelper#886]
I understand fixed width files are not necessarily CSV files... Can CsvHelper add support for fixed width files?

http://www.softinterface.com/Convert-XLS/Features/Fixed-Width-Text-File-Definition.htm

**Comment by jamesbascle** [comment]
I believe the plan for that is to have contrib packages for various
rectangular file formats that don't fit for csv. There is an Excel one at
the moment.

**Comment by JoshClose** [comment]
There are at least 2 Excel ones that I know of. I'm actually planning on writing a fixed width parser at some point, since it's so close to a CSV file. It'll probably be a while before that happens though.

**Comment by reloaded** [comment]
Thanks for the quick response. I've got the need to use fixed width alongside CSV reading/writing. It's a shame that fixed width is not in the library yet.. But I understand. I'm probably the only one who is working on a product that needs support for fixed width over CSV. 

I'm astonished by how quickly issues get responses in this repository. Keep up the amazing community support fellas.

**Comment by jamesbascle** [comment]
Correct me if I'm wrong Josh, but all someone needs to do in a contrib
library for csvhelper is to implement another parser, no?  Or is there an
entire replacement of most of the API?  I haven't looked at the excel libs
but once or twice.

**Comment by JoshClose** [comment]
I believe they have a Reader/Writer that inherits CsvReader/CsvWriter, but I don't remember for sure. 

As far as fixed width goes, you would need a `FixedWidthParser` that is used instead. You would also need to have some extra mapping or configuration so that you could specify the width of each column, the padding character, and maybe a few other things.

I think for CsvHelper to really be able to be built on top of, it would need to have things separated out a bit. There is a little bit too much CSV specific stuff in there. It would be nice to have more basic functionality that you build upon, and which there are CSV specific and fixed-width specific classes that inherit from the base functionality, so you don't have all the extra cruft from other implementations.
