### ISSUE TITLE
When using ConvertUsing in ClassMap referenced by other ClassMap get a runtime exception

### ISSUE THREAD

**Issue by sacha-br** [JoshClose/CsvHelper#889]
```cs
public sealed class ReportPatientModelMap : ClassMap<Patient>
    {
        public ReportPatientModelMap()
        {
            Map(m => m.Id).Name("Id");
            Map(m => m.FullName).Name("FullName");
            //...
            References<RegisterStatusModelMap>(m => m.RegisterStatus);            
        }
    }
    public sealed class RegisterStatusModelMap : ClassMap<RegisterStatus>
    {
        public RegisterStatusModelMap()
        {
		//...
		Map(m => m.Reason).Name("Reason").ConvertUsing(reason => reason.Reason.Code == "other" ? reason.AnotherReason : reason.Reason.Definition);
        }
    }
```

At debug has found out, that ConvertUsing expects that in expression will be caused with parameter RegisterStatus, but it is transferred Patient

**Comment by JoshClose** [comment]
Are you reading or writing?

**Comment by sacha-br** [comment]
>Are you reading or writing?  

writing

**Comment by JoshClose** [comment]
It will work if you don't use `References`. Try this.

```cs
public class ReportPatientModelMap : ClassMap<Patient>
{
    public ReportPatientModelMap()
    {
        Map(m => m.Id);
        Map(m => m.FullName);
        Map(m => m.RegisterStatus.Reason).ConvertUsing(patient => patient.RegisterStatus.Reason == "other" ? "reason 1" : "reason 2");
    }
}
```

**Comment by JoshClose** [comment]
The example I created didn't have as many sub object, but I think you'll get the idea.

**Comment by JoshClose** [comment]
I will look into this as a possible bug. This might just be a caveat/limitation though.

**Comment by sacha-br** [comment]
As expected without reference, everything works.

**Comment by JoshClose** [comment]
I think this is just a caveat. The problem is doing `ConvertUsing` you need to specify a member that is passed in. When doing sub property like `Map(m => m.A.B.C.Name)`, the object is a member access for type `A`, but it goes down the chain to find `A.B.C`. When doing a references instead, it's doing just `Map(m =>m .Name)` where m is C. I can't seem to find a way for the type to be correct when evaluating the expression when using `References`. I could significantly change how `References` works to it requires some types passed down for it to work, but that's a bad idea. Using `References` isn't the recommended way anyways.

I'm going to put a note in the XML docs for `Reference` saying it's meant for internal use, and `ConvertUsing` wont' work properly when using it.
