### ISSUE TITLE
Read DateTime of csv in correct Format

### ISSUE THREAD

**Issue by LucidSkyWalker** [JoshClose/CsvHelper#899]
I have a csv file containing a Date and want to read it directly in the correct format as I want to sort the rows by date afterwards.
I read through all the issues in your GIT but could not manage to do that...
Here's what I tried:

Store.cs
```
 public class Store
    {
        public String Type { get; set; }
        public String Quantity { get; set; }
        public DateTime Closed { get; set; }
    }
```
Program.cs
```
internal class Program
    {
        private static void Main(string[] args)
        {
            using (var sr = new StreamReader(@"file.csv", System.Text.Encoding.Unicode))
            {
                var reader = new CsvReader(sr);
                reader.Configuration.RegisterClassMap<StoreMap>();
                //CSVReader will now read the whole file into an enumerable
                IEnumerable<Store> records = reader.GetRecords<Store>();
                
                
                foreach (Store record in records) 
                {
                           // No code yet           
                }
            }
        }
    }
    public class StoreMap : CsvClassMap<Store>
    {
        CultureInfo en = new CultureInfo("en-US");
        public override void CreateMap()
        {
            Map(m => m.Type);
            Map(m => m.Quantity);
            Map(m => DateTime.ParseExact(m.Closed, "G", en.DateTimeFormat); });
        }
    }
```
The Problem is that I cannot convert String <=> DateTime that way...

The DateTime of my csv file is in format("G").

All options I read were suggesting something like:
csv.Configuration.TypeConverterOptionsCache.GetOptions<DateTime>().Formats = new[] { "G" };

Unfortunatly I dont have the TypeConverterOptions in my CSVHelper.

How can I tell CsvHelper that the read date is in Format("G") and use a DateTime Property in my class?

Thank you so so much for your help!

**Comment by JoshClose** [comment]
If you just need to change the format, you can do this:

```cs
Map(m => m.Closed).TypeConverterOptions.Format("G");
```

**Comment by PassiB91** [comment]
Hi Josh,

thank you for your fast reply!
I cannot use:
`.TypeConverterOptions.Format("G");`
as it doesnt exist in my CsvHelper?

To make the CsvReader work I have to change the property of my "Store" class to:
`public String Closed { get; set; }`

Than I tried:
`Map(m => m.Closed).TypeConverterOption("G");` 

which gives me no error by debugging but the Closed Property is still in type of "String" 
instead of "DateTime".

How can I tell the CsvReader that the String of the csv file is in dateformat "G",
and than map or convert the Property:
 `public String Closed { get; set; }`

to

`public DateTime Closed { get; set; }`

as I need the this column of my csv file in type "DateTime". 

I really appreciate your help!
Thank you so much for your effort!

**Comment by JoshClose** [comment]
What version of CsvHelper are you using?

**Comment by JoshClose** [comment]
I'm not sure if "G" is a valid format. I'm able to use custom formatting though. Make sure your format works with `DateTime.ParseExact`.

```cs
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,Name,Date");
        writer.WriteLine("1,one,1_2_18");
        writer.WriteLine("2,two,9_4_17");
        writer.Flush();
        stream.Position = 0;
        
        csv.Configuration.RegisterClassMap<TestMap>();
        csv.GetRecords<Test>().ToList().Dump();
    }
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
    public DateTime Date { get; set; }
}

public sealed class TestMap : ClassMap<Test>
{
    public TestMap()
    {
        Map(m => m.Id);
        Map(m => m.Name);
        Map(m => m.Date).TypeConverterOption.Format("M_d_yy");
    }
}
```

**Comment by mucalo** [comment]
Hello, I am trying this exact implementation:

In my class I have:

`public DateTime EstablishedDate { get; set; }`

In my map I have:

`Map(m => m.EstablishedDate).Name("COM_EstablishedDate").TypeConverterOption.Format("yyyyMMdd");`

In the file, the dates are:
yyyyMMdd (e.g. 20140429, 20140514...)

And I get an "String was not recognized as a valid DateTime".

Help?

Additional questions:
- is there a way to, if there is an error in some row, just skip that row and move on to the next one?
- is there a way to, if there is an error in some row, to get more detailed info about it? E.g. instead of "String was not recognized..." to get something "In the CSV line XX in column YY got 'krljghuh' and expected a DateTime value" :)

Thanks in advance!

**Comment by mucalo** [comment]
Also - on a similar note, can I make it try and parse each row as a DateTime, but if it can't, not to throw an error, just to add NULL?

**Comment by JoshClose** [comment]
@mucalo Your example seems to work fine for me.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name,Date");
		writer.WriteLine("1,one,20140429");
		writer.WriteLine("2,two,20140514");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public DateTime Date { get; set; }
}

public sealed class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.Date).TypeConverterOption.Format("yyyyMMdd");
	}
}
```

You can have it not throw an error by using this  configuration.

```cs
csv.Configuration.ReadingExceptionOccurred = ex => 
{
	// Do something instead of throwing an exception.
}
```

If you want to check the state during an error, you can look in `csv.Context`.

**Comment by mucalo** [comment]
Hey, John,

Thanks for that, it seems the error was elsewhere.
Can you give an example of processing an exception like this?

e.g. in a column that throws an error write NULL instead of the piece of data causing an exception?

Thanks in advance!
