### ISSUE TITLE
I need your help. Reading and writing from a file in DataGridView.

### ISSUE THREAD

**Issue by panigo** [JoshClose/CsvHelper#903]
Help me please!!! Do not read or write files. Thank you.
https://yadi.sk/i/bnIMo_Ww3RdY8p
https://yadi.sk/i/nvfGc7oU3RdYAN
Error reading file ...
https://yadi.sk/i/1kne8wrw3Rf9oo

**Comment by JoshClose** [comment]
`GetRecord<Student>()` is only going to get a single record. Is that what you want? Or do you want all the records assigned to the `DataSource`?

You're getting this error because when using `GetRecord<T>` you need to call `Read()` first. If you do `GetRecords<T>` (multiple), it will give you all the records without having to manually call read. `GetRecords<T>` returns an `IEnumerable` which is forward only, so if you're doing anything that is reading it multiple times, you might want to put it into another structure like a list. `GetRecords<Student>().ToList()`.

**Comment by panigo** [comment]
Thank you. Reading from a file works! Please tell me why the write to the file does not work, what did I do wrong? Writes only 3 characters.

**Comment by JoshClose** [comment]
If you're going to use `WriteRecord` for each row instead of using `WriteRecords` and passing the whole `IEnumerable`, you'll need to call `NextRecord` after each row has finished writing.

http://joshclose.github.io/CsvHelper/writing#writing-a-single-record

**Comment by panigo** [comment]
I am grateful for the help. Understood. Thank you.
