### ISSUE TITLE
Change delimiter to use culture specific list separator

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#918]
This may need to be switched to use `CultureInfo.CurrentCulture.TextInfo.ListSeparator` by default. This library should just work out of the box, but doesn't for some cultures.

All unit tests would need to specifically set the delimiter to work in other cultures, or the delimiter being written would have to change to `CultureInfo.CurrentCulture.TextInfo.ListSeparator`. The former is probably easier.

#610

**Comment by jamesdoran** [comment]
Hi @JoshClose,

Thanks for all your hard work on this library, it's made my life a lot easier. 

I just ran into this same issue when doing some testing for using our tool in Sweden. When saving a spreadsheet from Excel running in Sweden region, a semi-colon is used instead of a comma for separation:

x;y;z
-31,92224;138,587384;10
-32,93503;137,587384;10
-33,92224;136,5936658;10

When I then try and read this in to the tool, the commas used for decimal places deserialise just fine, but it's not happy with the semi-colon. I was able to fix with the following line (thanks to your suggestion):

`reader.Configuration.Delimiter = CultureInfo.CurrentCulture.TextInfo.ListSeparator;`

James

**Comment by JoshClose** [comment]
This is complete and will be in version 10.0.0 in nuget.

**Comment by francescomazzurco** [comment]
Hi @JoshClose,

when I set the `reader.Configuration.CultureInfo`, I wourd expect the `reader.Configuration.Delimiter` to be automatically updated as well, coherently to the CultureInfo I just chose. However, this is not the case.

Is this (not) done on purpose?

Thanks

**Comment by JoshClose** [comment]
It will if you pass the `CultureInfo` into the constructor of `Configuration`. Otherwise, they are separate configs. Some people use tabs and other things. It would be weird if you set a `Delimiter`, then set the `CultureInfo`, and it changed on you.

**Comment by francescomazzurco** [comment]
Makes sense, thanks for the quick answer

**Comment by JoshClose** [comment]
You're welcome!

**Comment by igitur** [comment]
As it goes with people logging issues, you'll see a lot more people complain about the current way a library is working (and in this case the way the default separator is treated) vs the number of people who support it. 

I, for one, totally agreed with you that CSV implies `comma separated values` and that any interpretation by Excel otherwise is a move away from the standard. So I believe this change was wrong. And I accept that many people here disagree with me. 

To illustrate it, the upgrade to CsvHelper v10 broke some of our code. We have Windows services running on service accounts and nobody has really cared about their regional settings, because CSV parsing has worked flawlessly under the service accounts as they did under the developer's accounts in the dev environment. Suddenly, after upgrading to v10, parsing started failing, with quite cryptic messages about failing to parse the headers. Now I found the real problem and it's going to be quite a mission to change the default regional settings for all the service accounts in production and non-production environments. 

So yeah... I don't think this change was worth the trouble it caused.

**Comment by JoshClose** [comment]
It's going to change back. Follow this thread. https://github.com/JoshClose/CsvHelper/issues/1203
