### ISSUE TITLE
Is there a way to write a column or not  depending if it is null

### ISSUE THREAD

**Issue by jfbenavid** [JoshClose/CsvHelper#957]
Good afternoon, 

As the title says, how can I write or not a field depending if this field is null.

Thanks for your help.

I have my ClassMap where I Define the next:

```csharp
public class BankReportMap : ClassMap<ReportResult>
    {
        public BankReportMap()
        {
            Map(m => m.Operation).Index(0).Name("OPERACION"); //this shouldn't be in the csv when the field comes null
            Map(m => m.TransactionNumber).Index(1).TypeConverter<TransactionConverter>().Name("TICKET USER");
            Map(m => m.Operator).Index(2).Name("OPERADOR");
            Map(m => m.Phone).Index(2).Name("TELEFONO");
            Map(m => m.State).Index(2).Name("ESTADO");
            Map(m => `m.StateDescription).Index(2).Name("DESCRIPCION` DEL ESTADO");
            Map(m => m.ArrivalDate).Index(2).Name("FECHA DE LLEGADA");
            Map(m => m.SendGatewayDate).Index(2).Name("FECHA DE ENVIO");
        }
    }

**Comment by JoshClose** [comment]
So you want to not write the field at all instead no value? Meaning `2,3` instead of `,23`?

I would highly recommend against doing this. Just let it write no value. If you do it per field, that means some rows may have it, some not, which will be a disaster to read.

If you want it to happen for row, then you can use the `.Ignore()` method on the map. Just add a constructor parameter to the map and pass in whether it should be ignored or not.

**Comment by JoshClose** [comment]
Ok, then passing a flag into the constructor of the map to ignore should work then.
